/**
 * Destination intelligence for the demo seed.
 *
 * Every price in here is a *cost* (what the agency pays a supplier), per
 * person unless the unit says otherwise — package.basePrice is a vendor-cost
 * total and sell_price is generated as cost + margin by the database, so
 * mixing retail prices in here would double-count the margin.
 *
 * Rates are plausible 2026 trade rates for a Colombo-based DMC: value
 * destinations (Sri Lanka, Vietnam, Nepal) sit low, premium ones (Maldives,
 * Japan, Kenya) sit high. Meals are per person per sitting.
 */

const d = (o) => o;

export const DESTINATIONS = {
  sriLanka: d({
    label: 'Sri Lanka',
    country: 'Sri Lanka',
    region: 'South Asia',
    airport: { code: 'CMB', name: 'Bandaranaike International Airport', city: 'Colombo' },
    meals: { breakfast: 9, lunch: 13, dinner: 18 },
    rates: { carPerKm: 0.42, vanPerKm: 0.6, trainPerPerson: 12, boatPerPerson: 26, flightPerPerson: 0, busPerKm: 0.3 },
    hotels: [
      { name: 'Cinnamon Grand Colombo', city: 'Colombo', roomType: 'Deluxe Room', nightly: 165 },
      { name: 'Heritance Kandalama', city: 'Dambulla', roomType: 'Superior Room', nightly: 190 },
      { name: 'The Grand Kandyan', city: 'Kandy', roomType: 'Deluxe Room', nightly: 145 },
      { name: 'Heritance Tea Factory', city: 'Nuwara Eliya', roomType: 'Superior Room', nightly: 175 },
      { name: 'Cinnamon Wild Yala', city: 'Yala', roomType: 'Chalet', nightly: 210 },
      { name: 'Taj Bentota Resort & Spa', city: 'Bentota', roomType: 'Garden View Room', nightly: 155 },
    ],
    places: [
      { name: 'Colombo', type: 'CITY' }, { name: 'Negombo', type: 'CITY' },
      { name: 'Sigiriya', type: 'ATTRACTION', cost: 30 }, { name: 'Dambulla', type: 'CITY' },
      { name: 'Kandy', type: 'CITY' }, { name: 'Nuwara Eliya', type: 'CITY' },
      { name: 'Ella', type: 'CITY' }, { name: 'Yala', type: 'REGION' },
      { name: 'Galle', type: 'CITY' }, { name: 'Bentota', type: 'REGION' },
      { name: 'Mirissa', type: 'CITY' }, { name: 'Anuradhapura', type: 'CITY' },
      { name: 'Polonnaruwa', type: 'CITY' }, { name: 'Trincomalee', type: 'CITY' },
    ],
    activities: [
      { name: 'Airport Meet and Greet', cost: 0 },
      { name: 'Colombo city sightseeing', cost: 0 },
      { name: 'Climbing Sigiriya Lion Rock', cost: 30 },
      { name: 'Dambulla Cave Temple visit', cost: 15 },
      { name: 'Minneriya National Park Safari', cost: 55 },
      { name: 'Temple of the Sacred Tooth Relic visit', cost: 12 },
      { name: 'Cultural Dance Show', cost: 10 },
      { name: 'Guided Tea Plantation and Factory Tour', cost: 18 },
      { name: 'Train ride to Ella', cost: 14 },
      { name: 'Nine Arch Bridge walk', cost: 0 },
      { name: 'Little Adam\u2019s Peak hike', cost: 0 },
      { name: 'Yala National Park jeep safari', cost: 60 },
      { name: 'Galle Fort walking tour', cost: 0 },
      { name: 'Madu River boat safari', cost: 25 },
      { name: 'Morning whale and dolphin watching cruise', cost: 45 },
      { name: 'Balapitiya turtle hatchery visit', cost: 8 },
      { name: 'Stilt fishing photo stop', cost: 0 },
      { name: 'Galle Face Green sunset walk', cost: 0 },
      { name: 'Cooking class with a local family', cost: 35 },
    ],
  }),

  maldives: d({
    label: 'Maldives',
    country: 'Maldives',
    region: 'South Asia',
    airport: { code: 'MLE', name: 'Velana International Airport', city: 'Malé' },
    meals: { breakfast: 18, lunch: 28, dinner: 42 },
    rates: { carPerKm: 0.6, vanPerKm: 0.8, trainPerPerson: 0, boatPerPerson: 60, flightPerPerson: 260, busPerKm: 0 },
    hotels: [
      { name: 'Baros Maldives', city: 'North Malé Atoll', roomType: 'Water Villa', nightly: 620 },
      { name: 'Coco Palm Dhuni Kolhu', city: 'Baa Atoll', roomType: 'Beach Villa', nightly: 410 },
      { name: 'Filitheyo Island Resort', city: 'Faafu Atoll', roomType: 'Deluxe Villa', nightly: 360 },
    ],
    places: [
      { name: 'Mal\u00e9', type: 'CITY' }, { name: 'North Mal\u00e9 Atoll', type: 'REGION' },
      { name: 'Baa Atoll', type: 'REGION' }, { name: 'Faafu Atoll', type: 'REGION' },
      { name: 'Hulhumal\u00e9', type: 'CITY' },
    ],
    activities: [
      { name: 'Seaplane transfer to resort', cost: 250 },
      { name: 'Snorkeling orientation', cost: 40 },
      { name: 'Guided house-reef snorkeling', cost: 45 },
      { name: 'Sunset dolphin cruise', cost: 70 },
      { name: 'Scuba diving \u2013 two-tank dive', cost: 130 },
      { name: 'Sandbank picnic', cost: 85 },
      { name: 'Overwater dinner experience', cost: 120 },
      { name: 'Couples spa ritual', cost: 180 },
      { name: 'Sunset fishing excursion', cost: 55 },
      { name: 'Manta ray and whale shark excursion', cost: 140 },
    ],
  }),

  thailand: d({
    label: 'Thailand',
    country: 'Thailand',
    region: 'Southeast Asia',
    airport: { code: 'BKK', name: 'Suvarnabhumi Airport', city: 'Bangkok' },
    meals: { breakfast: 8, lunch: 12, dinner: 17 },
    rates: { carPerKm: 0.4, vanPerKm: 0.58, trainPerPerson: 10, boatPerPerson: 30, flightPerPerson: 85, busPerKm: 0.28 },
    hotels: [
      { name: 'Chatrium Hotel Riverside Bangkok', city: 'Bangkok', roomType: 'Deluxe River View', nightly: 120 },
      { name: 'Riva Surya Bangkok', city: 'Bangkok', roomType: 'Deluxe Room', nightly: 135 },
      { name: 'Rachamankha Chiang Mai', city: 'Chiang Mai', roomType: 'Superior Room', nightly: 150 },
      { name: 'The Shore at Katathani', city: 'Phuket', roomType: 'Pool Villa', nightly: 320 },
      { name: 'Railay Princess Resort', city: 'Krabi', roomType: 'Deluxe Room', nightly: 110 },
    ],
    places: [
      { name: 'Bangkok', type: 'CITY' }, { name: 'Chiang Mai', type: 'CITY' },
      { name: 'Phuket', type: 'CITY' }, { name: 'Krabi', type: 'CITY' },
      { name: 'Phi Phi Islands', type: 'REGION' }, { name: 'Chiang Rai', type: 'CITY' },
      { name: 'Damnoen Saduak', type: 'CITY' }, { name: 'Ayutthaya', type: 'CITY' },
    ],
    activities: [
      { name: 'Grand Palace tour', cost: 18 },
      { name: 'Chao Phraya dinner cruise', cost: 45 },
      { name: 'Floating market visit', cost: 22 },
      { name: 'Doi Suthep temple visit', cost: 12 },
      { name: 'Thai cooking class', cost: 40 },
      { name: 'Ethical elephant sanctuary visit', cost: 65 },
      { name: 'Phi Phi island-hopping by speedboat', cost: 55 },
      { name: 'James Bond Island canoe tour', cost: 50 },
      { name: 'Ayutthaya historical park tour', cost: 30 },
      { name: 'Traditional Thai massage', cost: 25 },
      { name: 'Night bazaar walk', cost: 0 },
      { name: 'Muay Thai match tickets', cost: 35 },
    ],
  }),

  bali: d({
    label: 'Bali, Indonesia',
    country: 'Indonesia',
    region: 'Southeast Asia',
    airport: { code: 'DPS', name: 'Ngurah Rai International Airport', city: 'Denpasar' },
    meals: { breakfast: 8, lunch: 12, dinner: 16 },
    rates: { carPerKm: 0.38, vanPerKm: 0.55, trainPerPerson: 0, boatPerPerson: 32, flightPerPerson: 70, busPerKm: 0.26 },
    hotels: [
      { name: 'Alaya Resort Ubud', city: 'Ubud', roomType: 'Deluxe Room', nightly: 140 },
      { name: 'The Kayon Jungle Resort', city: 'Ubud', roomType: 'Suite with Plunge Pool', nightly: 290 },
      { name: 'Katamama Seminyak', city: 'Seminyak', roomType: 'Suite', nightly: 340 },
      { name: 'Segara Village Sanur', city: 'Sanur', roomType: 'Garden Bungalow', nightly: 130 },
      { name: 'Adiwana Bisma', city: 'Ubud', roomType: 'Deluxe Room', nightly: 155 },
    ],
    places: [
      { name: 'Ubud', type: 'CITY' }, { name: 'Seminyak', type: 'CITY' },
      { name: 'Nusa Penida', type: 'CITY' }, { name: 'Tegallalang', type: 'CITY' },
      { name: 'Tirta Empul', type: 'CITY' }, { name: 'Uluwatu', type: 'ATTRACTION' },
      { name: 'Sanur', type: 'CITY' }, { name: 'Kintamani', type: 'REGION' },
    ],
    activities: [
      { name: 'Balinese cooking class', cost: 35 },
      { name: 'Tegallalang rice terrace walk', cost: 0 },
      { name: 'Tirta Empul purification ritual', cost: 12 },
      { name: 'Ubud Monkey Forest visit', cost: 10 },
      { name: 'Mount Batur sunrise trek', cost: 55 },
      { name: 'Uluwatu Temple sunset & Kecak dance', cost: 28 },
      { name: 'Nusa Penida island day trip', cost: 65 },
      { name: 'Kelingking Beach viewpoint', cost: 0 },
      { name: 'Couples spa ritual', cost: 90 },
      { name: 'White-water rafting on the Ayung', cost: 45 },
      { name: 'Silver-smithing workshop', cost: 40 },
      { name: 'Sunrise yoga session', cost: 20 },
      { name: 'Jimbaran seafood beach dinner', cost: 48 },
    ],
  }),

  uae: d({
    label: 'Dubai, UAE',
    country: 'United Arab Emirates',
    region: 'Middle East',
    airport: { code: 'DXB', name: 'Dubai International Airport', city: 'Dubai' },
    meals: { breakfast: 16, lunch: 24, dinner: 38 },
    rates: { carPerKm: 0.65, vanPerKm: 0.85, trainPerPerson: 8, boatPerPerson: 55, flightPerPerson: 130, busPerKm: 0.4 },
    hotels: [
      { name: 'Address Beach Resort', city: 'Dubai', roomType: 'Deluxe Sea View', nightly: 420 },
      { name: 'Rove Downtown', city: 'Dubai', roomType: 'Rover Room', nightly: 150 },
      { name: 'Atlantis The Palm', city: 'Dubai', roomType: 'Ocean Deluxe', nightly: 520 },
      { name: 'Anantara Downtown Dubai', city: 'Dubai', roomType: 'Premier Room', nightly: 260 },
      { name: 'Qasr Al Sarab Desert Resort', city: 'Abu Dhabi', roomType: 'Desert View Room', nightly: 480 },
    ],
    places: [
      { name: 'Downtown Dubai', type: 'CITY' }, { name: 'Dubai Marina', type: 'CITY' },
      { name: 'Dubai Desert', type: 'REGION' }, { name: 'Abu Dhabi', type: 'CITY' },
      { name: 'Palm Jumeirah', type: 'REGION' }, { name: 'Old Dubai', type: 'CITY' },
      { name: 'Sharjah', type: 'CITY' },
    ],
    activities: [
      { name: 'Burj Khalifa observation deck', cost: 45 },
      { name: 'Dubai Fountain show', cost: 0 },
      { name: 'Desert safari with BBQ dinner', cost: 65 },
      { name: 'Dune bashing', cost: 55 },
      { name: 'Camel ride', cost: 25 },
      { name: 'Dubai Mall & aquarium visit', cost: 40 },
      { name: 'Dubai Creek abra ride', cost: 5 },
      { name: 'Gold and spice souk walk', cost: 0 },
      { name: 'Sheikh Zayed Grand Mosque visit', cost: 0 },
      { name: 'Ferrari World Abu Dhabi', cost: 95 },
      { name: 'Museum of the Future', cost: 42 },
      { name: 'Dubai Marina dhow cruise dinner', cost: 58 },
      { name: 'Ski Dubai snow park', cost: 65 },
      { name: 'Global Village entry', cost: 20 },
    ],
  }),

  japan: d({
    label: 'Japan',
    country: 'Japan',
    region: 'East Asia',
    airport: { code: 'NRT', name: 'Narita International Airport', city: 'Tokyo' },
    meals: { breakfast: 14, lunch: 20, dinner: 34 },
    rates: { carPerKm: 0.9, vanPerKm: 1.1, trainPerPerson: 60, boatPerPerson: 45, flightPerPerson: 0, busPerKm: 0.55 },
    hotels: [
      { name: 'Mitsui Garden Hotel Ginza', city: 'Tokyo', roomType: 'Moderate Double', nightly: 220 },
      { name: 'Hotel Granvia Kyoto', city: 'Kyoto', roomType: 'Superior Double', nightly: 260 },
      { name: 'Hakone Ginyu ryokan', city: 'Hakone', roomType: 'Japanese-style Room', nightly: 420 },
      { name: 'Cross Hotel Osaka', city: 'Osaka', roomType: 'Deluxe Twin', nightly: 190 },
    ],
    places: [
      { name: 'Tokyo', type: 'CITY' }, { name: 'Kyoto', type: 'CITY' },
      { name: 'Osaka', type: 'CITY' }, { name: 'Hakone', type: 'CITY' },
      { name: 'Mt Fuji', type: 'ATTRACTION' }, { name: 'Nara', type: 'CITY' },
      { name: 'Hiroshima', type: 'CITY' }, { name: 'Kanazawa', type: 'CITY' },
      { name: 'Takayama', type: 'CITY' },
    ],
    activities: [
      { name: 'Meiji Shrine visit', cost: 0 },
      { name: 'Shibuya Crossing walk', cost: 0 },
      { name: 'Tsukiji Outer Market breakfast tour', cost: 35 },
      { name: 'Fushimi Inari shrine walk', cost: 0 },
      { name: 'Kinkaku-ji Golden Pavilion', cost: 5 },
      { name: 'Gion geisha district evening walk', cost: 40 },
      { name: 'Arashiyama Bamboo Grove visit', cost: 0 },
      { name: 'Nara deer park day trip', cost: 25 },
      { name: 'JR Pass activation and rail travel', cost: 210 },
      { name: 'Mt Fuji and Lake Ashi day trip', cost: 75 },
      { name: 'Onsen ryokan experience', cost: 60 },
      { name: 'Osaka Castle visit', cost: 8 },
      { name: 'Dotonbori food crawl', cost: 45 },
      { name: 'Traditional tea ceremony', cost: 40 },
      { name: 'Miyajima ferry and Itsukushima Shrine', cost: 30 },
    ],
  }),

  singapore: d({
    label: 'Singapore',
    country: 'Singapore',
    region: 'Southeast Asia',
    airport: { code: 'SIN', name: 'Changi Airport', city: 'Singapore' },
    meals: { breakfast: 14, lunch: 18, dinner: 30 },
    rates: { carPerKm: 0.85, vanPerKm: 1.0, trainPerPerson: 5, boatPerPerson: 40, flightPerPerson: 0, busPerKm: 0.5 },
    hotels: [
      { name: 'Pan Pacific Singapore', city: 'Marina Bay', roomType: 'Deluxe Room', nightly: 280 },
      { name: 'Village Hotel Sentosa', city: 'Sentosa', roomType: 'Deluxe Room', nightly: 220 },
      { name: 'Carlton City Hotel', city: 'Chinatown', roomType: 'Deluxe Room', nightly: 190 },
    ],
    places: [
      { name: 'Marina Bay', type: 'CITY' }, { name: 'Sentosa', type: 'REGION' },
      { name: 'Chinatown', type: 'CITY' }, { name: 'Kampong Glam', type: 'CITY' },
      { name: 'Jurong', type: 'CITY' }, { name: 'Mandai', type: 'REGION' },
    ],
    activities: [
      { name: 'Gardens by the Bay & Supertree show', cost: 28 },
      { name: 'Marina Bay Sands SkyPark', cost: 32 },
      { name: 'Universal Studios Singapore', cost: 82 },
      { name: 'S.E.A. Aquarium', cost: 42 },
      { name: 'Singapore Zoo with breakfast in the wild', cost: 65 },
      { name: 'Night Safari', cost: 55 },
      { name: 'Sentosa cable car ride', cost: 25 },
      { name: 'Singapore Flyer', cost: 40 },
      { name: 'Hawker food trail with a guide', cost: 45 },
      { name: 'River Wonders', cost: 38 },
    ],
  }),

  vietnam: d({
    label: 'Vietnam',
    country: 'Vietnam',
    region: 'Southeast Asia',
    airport: { code: 'SGN', name: 'Tan Son Nhat International Airport', city: 'Ho Chi Minh City' },
    meals: { breakfast: 6, lunch: 10, dinner: 15 },
    rates: { carPerKm: 0.35, vanPerKm: 0.5, trainPerPerson: 22, boatPerPerson: 45, flightPerPerson: 90, busPerKm: 0.24 },
    hotels: [
      { name: 'La Siesta Premium Hang Be', city: 'Hanoi', roomType: 'Deluxe Room', nightly: 95 },
      { name: 'Silk Path Grand Resort', city: 'Hoi An', roomType: 'Deluxe Room', nightly: 120 },
      { name: 'Hotel des Arts Saigon', city: 'Ho Chi Minh City', roomType: 'Deluxe Room', nightly: 145 },
      { name: 'Bhaya Classic Cruise', city: 'Ha Long Bay', roomType: 'Deluxe Cabin', nightly: 240 },
    ],
    places: [
      { name: 'Hanoi', type: 'CITY' }, { name: 'Ha Long Bay', type: 'REGION' },
      { name: 'Hoi An', type: 'CITY' }, { name: 'Ho Chi Minh City', type: 'CITY' },
      { name: 'Hue', type: 'CITY' }, { name: 'Can Tho', type: 'CITY' },
      { name: 'Da Nang', type: 'CITY' }, { name: 'Ninh Binh', type: 'CITY' },
    ],
    activities: [
      { name: 'Old Quarter street food walk', cost: 25 },
      { name: 'Ha Long Bay overnight cruise', cost: 180 },
      { name: 'Hoi An Ancient Town lantern walk', cost: 8 },
      { name: 'Cooking class in a Hoi An garden', cost: 30 },
      { name: 'Cu Chi Tunnels guided visit', cost: 25 },
      { name: 'Mekong Delta boat and bicycle tour', cost: 45 },
      { name: 'Hue Imperial Citadel tour', cost: 16 },
      { name: 'Hai Van Pass motorbike ride', cost: 40 },
      { name: 'Water puppet theatre', cost: 12 },
      { name: 'Marble Mountains visit', cost: 10 },
      { name: 'Tailor fitting in Hoi An', cost: 60 },
    ],
  }),

  nepal: d({
    label: 'Nepal',
    country: 'Nepal',
    region: 'South Asia',
    airport: { code: 'KTM', name: 'Tribhuvan International Airport', city: 'Kathmandu' },
    meals: { breakfast: 7, lunch: 10, dinner: 14 },
    rates: { carPerKm: 0.4, vanPerKm: 0.55, trainPerPerson: 0, boatPerPerson: 25, flightPerPerson: 180, busPerKm: 0.26 },
    hotels: [
      { name: 'Hotel Shanker Kathmandu', city: 'Kathmandu', roomType: 'Deluxe Room', nightly: 110 },
      { name: 'Fishtail Lodge Pokhara', city: 'Pokhara', roomType: 'Standard Room', nightly: 140 },
      { name: 'Yeti Mountain Home Namche', city: 'Namche Bazaar', roomType: 'Deluxe Room', nightly: 180 },
      { name: 'Club Himalaya Nagarkot', city: 'Nagarkot', roomType: 'Deluxe Room', nightly: 130 },
    ],
    places: [
      { name: 'Kathmandu', type: 'CITY' }, { name: 'Pokhara', type: 'CITY' },
      { name: 'Bhaktapur', type: 'CITY' }, { name: 'Nagarkot', type: 'CITY' },
      { name: 'Namche Bazaar', type: 'CITY' }, { name: 'Tengboche', type: 'CITY' },
      { name: 'Chitwan', type: 'REGION' }, { name: 'Lukla', type: 'CITY' },
    ],
    activities: [
      { name: 'Kathmandu Durbar Square tour', cost: 12 },
      { name: 'Boudhanath Stupa kora walk', cost: 5 },
      { name: 'Pashupatinath Temple visit', cost: 10 },
      { name: 'Bhaktapur old city walk', cost: 15 },
      { name: 'Pokhara Phewa Lake boat ride', cost: 12 },
      { name: 'Sarangkot sunrise viewpoint', cost: 10 },
      { name: 'Everest scenic mountain flight', cost: 220 },
      { name: 'Trek to Tengboche Monastery', cost: 0 },
      { name: 'Chitwan jungle safari', cost: 65 },
      { name: 'Momo cooking class', cost: 20 },
      { name: 'Paragliding in Pokhara', cost: 110 },
    ],
  }),

  turkey: d({
    label: 'Turkey',
    country: 'T\u00fcrkiye',
    region: 'Europe / Middle East',
    airport: { code: 'IST', name: 'Istanbul Airport', city: 'Istanbul' },
    meals: { breakfast: 10, lunch: 16, dinner: 24 },
    rates: { carPerKm: 0.5, vanPerKm: 0.68, trainPerPerson: 20, boatPerPerson: 35, flightPerPerson: 95, busPerKm: 0.32 },
    hotels: [
      { name: 'Levni Hotel Istanbul', city: 'Istanbul', roomType: 'Deluxe Room', nightly: 150 },
      { name: 'Museum Hotel Cappadocia', city: 'Cappadocia', roomType: 'Cave Suite', nightly: 340 },
      { name: 'DoubleTree by Hilton Kusadasi', city: 'Ku\u015fadas\u0131', roomType: 'Sea View Room', nightly: 130 },
      { name: 'Pamukkale Thermal Hotel', city: 'Pamukkale', roomType: 'Standard Room', nightly: 95 },
    ],
    places: [
      { name: 'Istanbul', type: 'CITY' }, { name: 'Cappadocia', type: 'REGION' },
      { name: 'Ephesus', type: 'ATTRACTION' }, { name: 'Pamukkale', type: 'ATTRACTION' },
      { name: 'Antalya', type: 'CITY' }, { name: 'Ku\u015fadas\u0131', type: 'CITY' },
      { name: 'Bursa', type: 'CITY' },
    ],
    activities: [
      { name: 'Hagia Sophia and Blue Mosque visit', cost: 35 },
      { name: 'Topkapi Palace tour', cost: 40 },
      { name: 'Bosphorus dinner cruise', cost: 55 },
      { name: 'Grand Bazaar walk with a guide', cost: 20 },
      { name: 'Cappadocia hot-air balloon flight', cost: 220 },
      { name: 'Goreme Open Air Museum', cost: 25 },
      { name: 'Underground city of Kaymakli', cost: 18 },
      { name: 'Ephesus ancient city tour', cost: 45 },
      { name: 'Pamukkale travertines and Hierapolis', cost: 30 },
      { name: 'Turkish bath (hamam) experience', cost: 45 },
      { name: 'Whirling dervish ceremony', cost: 35 },
      { name: 'Turkish cooking class', cost: 50 },
    ],
  }),

  egypt: d({
    label: 'Egypt',
    country: 'Egypt',
    region: 'North Africa',
    airport: { code: 'CAI', name: 'Cairo International Airport', city: 'Cairo' },
    meals: { breakfast: 9, lunch: 14, dinner: 20 },
    rates: { carPerKm: 0.4, vanPerKm: 0.55, trainPerPerson: 18, boatPerPerson: 50, flightPerPerson: 120, busPerKm: 0.28 },
    hotels: [
      { name: 'Steigenberger Pyramids Cairo', city: 'Cairo', roomType: 'Pyramid View Room', nightly: 165 },
      { name: 'Movenpick MS Sun Ray', city: 'Nile Cruise', roomType: 'Deluxe Cabin', nightly: 210 },
      { name: 'Sofitel Winter Palace Luxor', city: 'Luxor', roomType: 'Classic Room', nightly: 200 },
      { name: 'Steigenberger Tahrir', city: 'Cairo', roomType: 'Deluxe Room', nightly: 140 },
    ],
    places: [
      { name: 'Cairo', type: 'CITY' }, { name: 'Giza', type: 'ATTRACTION' },
      { name: 'Luxor', type: 'CITY' }, { name: 'Aswan', type: 'CITY' },
      { name: 'Abu Simbel', type: 'ATTRACTION' }, { name: 'Alexandria', type: 'CITY' },
      { name: 'Edfu', type: 'CITY' }, { name: 'Kom Ombo', type: 'ATTRACTION' },
    ],
    activities: [
      { name: 'Pyramids of Giza and Sphinx tour', cost: 40 },
      { name: 'Egyptian Museum guided visit', cost: 25 },
      { name: 'Grand Egyptian Museum entry', cost: 45 },
      { name: 'Khan el-Khalili bazaar walk', cost: 0 },
      { name: 'Nile felucca sail at sunset', cost: 30 },
      { name: 'Karnak and Luxor Temple tour', cost: 35 },
      { name: 'Valley of the Kings with Tutankhamun tomb', cost: 55 },
      { name: 'Abu Simbel day trip', cost: 110 },
      { name: 'Nubian village visit', cost: 35 },
      { name: 'Sound and light show at Karnak', cost: 30 },
      { name: 'Hot-air balloon over Luxor', cost: 130 },
    ],
  }),

  morocco: d({
    label: 'Morocco',
    country: 'Morocco',
    region: 'North Africa',
    airport: { code: 'CMN', name: 'Mohammed V International Airport', city: 'Casablanca' },
    meals: { breakfast: 9, lunch: 14, dinner: 22 },
    rates: { carPerKm: 0.45, vanPerKm: 0.62, trainPerPerson: 16, boatPerPerson: 30, flightPerPerson: 100, busPerKm: 0.3 },
    hotels: [
      { name: 'Riad Yasmine Marrakech', city: 'Marrakech', roomType: 'Riad Suite', nightly: 190 },
      { name: 'Riad Fes', city: 'Fez', roomType: 'Deluxe Room', nightly: 175 },
      { name: 'Kasbah Tombouctou', city: 'A\u00eft Ben Haddou', roomType: 'Kasbah Room', nightly: 120 },
      { name: 'Hotel Farah Rabat', city: 'Rabat', roomType: 'Superior Room', nightly: 130 },
    ],
    places: [
      { name: 'Marrakech', type: 'CITY' }, { name: 'Fez', type: 'CITY' },
      { name: 'Casablanca', type: 'CITY' }, { name: 'Chefchaouen', type: 'CITY' },
      { name: 'A\u00eft Ben Haddou', type: 'ATTRACTION' }, { name: 'Rabat', type: 'CITY' },
      { name: 'Merzouga', type: 'REGION' }, { name: 'Ouarzazate', type: 'CITY' },
    ],
    activities: [
      { name: 'Jemaa el-Fnaa square evening walk', cost: 0 },
      { name: 'Majorelle Garden and Berber Museum', cost: 18 },
      { name: 'Bahia Palace tour', cost: 10 },
      { name: 'Fez medina guided walk', cost: 30 },
      { name: 'Chouara leather tannery viewpoint', cost: 5 },
      { name: 'Chefchaouen blue city photo walk', cost: 0 },
      { name: 'Sahara camel trek and desert camp', cost: 120 },
      { name: 'Atlas Mountains day trip', cost: 65 },
      { name: 'Moroccan cooking class', cost: 45 },
      { name: 'Hammam and argan oil spa', cost: 55 },
      { name: 'Ouzoud Falls excursion', cost: 50 },
    ],
  }),

  kenya: d({
    label: 'Kenya',
    country: 'Kenya',
    region: 'East Africa',
    airport: { code: 'NBO', name: 'Jomo Kenyatta International Airport', city: 'Nairobi' },
    meals: { breakfast: 14, lunch: 22, dinner: 34 },
    rates: { carPerKm: 0.7, vanPerKm: 0.9, trainPerPerson: 25, boatPerPerson: 60, flightPerPerson: 320, busPerKm: 0.42 },
    hotels: [
      { name: 'Mara Serena Safari Lodge', city: 'Masai Mara', roomType: 'Standard Room', nightly: 380 },
      { name: 'Ashnil Mara Camp', city: 'Masai Mara', roomType: 'Luxury Tent', nightly: 450 },
      { name: 'Lake Nakuru Sopa Lodge', city: 'Lake Nakuru', roomType: 'Standard Room', nightly: 260 },
      { name: 'Amboseli Sopa Lodge', city: 'Amboseli', roomType: 'Standard Room', nightly: 270 },
    ],
    places: [
      { name: 'Nairobi', type: 'CITY' }, { name: 'Masai Mara', type: 'REGION' },
      { name: 'Lake Nakuru', type: 'REGION' }, { name: 'Amboseli', type: 'REGION' },
      { name: 'Lake Naivasha', type: 'REGION' }, { name: 'Diani Beach', type: 'REGION' },
    ],
    activities: [
      { name: 'Maasai Mara game drive', cost: 90 },
      { name: 'Great Migration river crossing viewing', cost: 120 },
      { name: 'Masai village cultural visit', cost: 35 },
      { name: 'Lake Nakuru flamingo and rhino drive', cost: 75 },
      { name: 'Amboseli elephant herds with Kilimanjaro views', cost: 85 },
      { name: 'Lake Naivasha boat safari', cost: 55 },
      { name: 'Hell\u2019s Gate cycling safari', cost: 60 },
      { name: 'Giraffe Centre and elephant orphanage', cost: 45 },
      { name: 'Hot-air balloon safari over the Mara', cost: 480 },
      { name: 'Bush dinner under the stars', cost: 95 },
    ],
  }),

  bhutan: d({
    label: 'Bhutan',
    country: 'Bhutan',
    region: 'South Asia',
    airport: { code: 'PBH', name: 'Paro International Airport', city: 'Paro' },
    meals: { breakfast: 12, lunch: 16, dinner: 22 },
    rates: { carPerKm: 0.55, vanPerKm: 0.72, trainPerPerson: 0, boatPerPerson: 30, flightPerPerson: 260, busPerKm: 0.34 },
    hotels: [
      { name: 'Zhiwa Ling Heritage', city: 'Paro', roomType: 'Deluxe Room', nightly: 280 },
      { name: 'Le Meridien Thimphu', city: 'Thimphu', roomType: 'Classic Room', nightly: 220 },
      { name: 'Punakha River Lodge', city: 'Punakha', roomType: 'Deluxe Room', nightly: 240 },
      { name: 'Dewachen Resort Paro', city: 'Paro', roomType: 'Deluxe Room', nightly: 250 },
    ],
    places: [
      { name: 'Paro', type: 'CITY' }, { name: 'Thimphu', type: 'CITY' },
      { name: 'Punakha', type: 'CITY' }, { name: 'Tiger\u2019s Nest', type: 'ATTRACTION' },
      { name: 'Wangdue', type: 'CITY' }, { name: 'Haa', type: 'REGION' },
    ],
    activities: [
      { name: 'Tiger\u2019s Nest (Taktsang) monastery hike', cost: 25 },
      { name: 'Paro Rinpung Dzong visit', cost: 15 },
      { name: 'Thimphu Buddha Dordenma viewpoint', cost: 0 },
      { name: 'National Textile Museum', cost: 10 },
      { name: 'Punakha Dzong visit', cost: 15 },
      { name: 'Dochula Pass with 108 chortens', cost: 0 },
      { name: 'Traditional hot-stone bath', cost: 40 },
      { name: 'Bhutanese cooking and chilli-cheese class', cost: 35 },
      { name: 'Archery lesson in local dress', cost: 30 },
      { name: 'Phobjikha Valley crane viewing', cost: 20 },
    ],
  }),

  europe: d({
    label: 'Europe (UK, France, Netherlands, Italy)',
    country: 'Europe',
    region: 'Europe',
    airport: { code: 'LHR', name: 'Heathrow Airport', city: 'London' },
    meals: { breakfast: 16, lunch: 24, dinner: 38 },
    rates: { carPerKm: 1.0, vanPerKm: 1.25, trainPerPerson: 95, boatPerPerson: 45, flightPerPerson: 130, busPerKm: 0.6 },
    hotels: [
      { name: 'The Tower Hotel London', city: 'London', roomType: 'Deluxe Room', nightly: 290 },
      { name: 'Hotel du Champ de Mars', city: 'Paris', roomType: 'Classic Double', nightly: 240 },
      { name: 'Hotel V Nesplein', city: 'Amsterdam', roomType: 'Deluxe Room', nightly: 260 },
      { name: 'Hotel Artemide Rome', city: 'Rome', roomType: 'Deluxe Room', nightly: 270 },
    ],
    places: [
      { name: 'London', type: 'CITY' }, { name: 'Paris', type: 'CITY' },
      { name: 'Amsterdam', type: 'CITY' }, { name: 'Rome', type: 'CITY' },
      { name: 'Brussels', type: 'CITY' }, { name: 'Versailles', type: 'ATTRACTION' },
      { name: 'Vatican City', type: 'ATTRACTION' },
    ],
    activities: [
      { name: 'Big Ben and Westminster walking tour', cost: 25 },
      { name: 'British Museum guided visit', cost: 30 },
      { name: 'London Eye ride', cost: 45 },
      { name: 'Eurostar rail crossing', cost: 110 },
      { name: 'Eiffel Tower summit access', cost: 48 },
      { name: 'Louvre Museum guided visit', cost: 55 },
      { name: 'Seine dinner cruise', cost: 85 },
      { name: 'Palace of Versailles day trip', cost: 65 },
      { name: 'Amsterdam canal cruise', cost: 30 },
      { name: 'Anne Frank House visit', cost: 20 },
      { name: 'Colosseum and Roman Forum tour', cost: 50 },
      { name: 'Vatican Museums and Sistine Chapel', cost: 60 },
      { name: 'Italian pasta-making class', cost: 70 },
    ],
  }),
};

/**
 * Packages the demo seed creates. Existing packages (pkg1–pkg7, the two the
 * package editor created, and anything a chat session made) are left exactly
 * as they are — these are additive.
 *
 * `days` is the itinerary. Short form per day:
 *   [title, description, places[], activities[], leg|null, meals, hotelIndex]
 * `leg` = [fromPlace, toPlace, km, mode] → one transport row for that day.
 * `meals` = [breakfast, lunch, dinner] as 0/1.
 * `hotelIndex` = index into that destination's hotels, or -1 for none.
 */
const F = (days) => days;

export const PACKAGE_BLUEPRINTS = [
  {
    key: 'sri-lanka-family-discovery',
    title: 'Sri Lanka Family Discovery',
    dest: 'sriLanka',
    category: 'FAMILY',
    days: 7,
    basePrice: 1580,
    marginType: 'PERCENTAGE',
    marginInput: 22,
    featured: true,
    rating: 4.7,
    views: 738,
    bookings: 21,
    inclusions: ['6 nights in family rooms', 'Daily breakfast and dinner', 'Private air-conditioned vehicle with English-speaking chauffeur guide', 'All entrance fees listed in the itinerary', 'Airport transfers'],
    exclusions: ['International flights', 'Lunch and beverages', 'Travel insurance', 'Optional excursions', 'Personal expenses and gratuities'],
    terms: 'A 25% deposit confirms the booking. Balance due 21 days before arrival. Free date changes up to 30 days before travel.',
    cover: 'https://images.unsplash.com/photo-1566296314736-6eaac1ca0cb9?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Colombo', 'Met on arrival at Bandaranaike International Airport and transferred to your Colombo hotel. Evening at leisure on Galle Face Green with your first taste of Sri Lankan street food.', ['Colombo'], ['Airport Meet and Greet', 'Galle Face Green sunset walk'], ['Colombo', 'Colombo', 32, 'VAN'], [0, 0, 1], 0],
      ['Sigiriya Rock Fortress and Minneriya Safari', 'Early drive to the Cultural Triangle. Climb the 5th-century Sigiriya fortress before an afternoon jeep safari in Minneriya, famous for its gathering of wild elephants.', ['Sigiriya', 'Dambulla'], ['Climbing Sigiriya Lion Rock', 'Minneriya National Park Safari'], ['Colombo', 'Sigiriya', 175, 'VAN'], [1, 1, 1], 1],
      ['Dambulla Cave Temples and Kandy', 'Explore the painted cave temples of Dambulla, then continue to the hill capital. Evening cultural dance performance and a visit to the Temple of the Sacred Tooth Relic.', ['Dambulla', 'Kandy'], ['Dambulla Cave Temple visit', 'Cultural Dance Show', 'Temple of the Sacred Tooth Relic visit'], ['Dambulla', 'Kandy', 72, 'VAN'], [1, 1, 1], 2],
      ['Kandy to Nuwara Eliya through Tea Country', 'Royal Botanical Gardens in the morning, then the winding climb into the tea hills. Guided plantation tour and tasting at a working factory.', ['Kandy', 'Nuwara Eliya'], ['Guided Tea Plantation and Factory Tour'], ['Kandy', 'Nuwara Eliya', 78, 'VAN'], [1, 1, 1], 3],
      ['Train to Ella and Little Adam\u2019s Peak', 'Sri Lanka\u2019s most beautiful rail journey, then an easy family hike to Little Adam\u2019s Peak with valley views.', ['Nuwara Eliya', 'Ella'], ['Train ride to Ella', 'Little Adam\u2019s Peak hike', 'Nine Arch Bridge walk'], ['Nuwara Eliya', 'Ella', 56, 'TRAIN'], [1, 0, 1], 3],
      ['Yala National Park Jeep Safari', 'Descend to the lowlands for an afternoon safari in Yala, home to leopards, sloth bears and elephants. Overnight at the park edge.', ['Yala'], ['Yala National Park jeep safari'], ['Ella', 'Yala', 128, 'VAN'], [1, 1, 1], 4],
      ['Galle Fort and Departure', 'Drive along the southern coast to the Dutch-built Galle Fort for a guided walk, then transfer to the airport via the expressway.', ['Galle'], ['Galle Fort walking tour'], ['Yala', 'Galle', 118, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'sri-lanka-culture-coast',
    title: 'Sri Lanka Culture & Coast Escape',
    dest: 'sriLanka',
    category: 'COUPLE',
    days: 6,
    basePrice: 1180,
    marginType: 'PERCENTAGE',
    marginInput: 24,
    featured: false,
    rating: 4.6,
    views: 412,
    bookings: 14,
    inclusions: ['5 nights in boutique hotels', 'Daily breakfast', 'Private car with chauffeur guide', 'Two guided excursions per day as listed', 'Airport transfers'],
    exclusions: ['International flights', 'Lunches, dinners and drinks', 'Travel insurance', 'Spa treatments and gratuities'],
    terms: '30% deposit on booking. Balance due 14 days before arrival. Low-season discounts available for May to October travel.',
    cover: 'https://images.unsplash.com/photo-1588598242260-0d4d1e4e6ecd?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival and Colombo by Night', 'Arrive into Colombo and settle into a city hotel. Sunset walk at Galle Face Green, followed by a rooftop dinner.', ['Colombo'], ['Airport Meet and Greet', 'Galle Face Green sunset walk'], ['Colombo', 'Colombo', 32, 'VAN'], [0, 0, 1], 0],
      ['Anuradhapura and the Cultural Triangle', 'Visit the sacred city of Anuradhapura with its dagobas and bodhi tree, one of the oldest continuously inhabited sites in Asia.', ['Anuradhapura', 'Sigiriya'], ['Colombo city sightseeing'], ['Colombo', 'Anuradhapura', 205, 'VAN'], [1, 1, 1], 1],
      ['Sigiriya at Sunrise and Dambulla', 'Climb Sigiriya in the cool of the morning, then the cave temples at Dambulla and a village lunch cooked over firewood.', ['Sigiriya', 'Dambulla'], ['Climbing Sigiriya Lion Rock', 'Dambulla Cave Temple visit'], ['Sigiriya', 'Dambulla', 18, 'CAR'], [1, 1, 1], 1],
      ['Kandy and the Hill Capital', 'Royal Botanical Gardens, the Temple of the Sacred Tooth Relic and an evening cultural performance.', ['Kandy'], ['Temple of the Sacred Tooth Relic visit', 'Cultural Dance Show'], ['Dambulla', 'Kandy', 72, 'VAN'], [1, 1, 1], 2],
      ['Tea Country and Nuwara Eliya', 'Climb into the tea hills, tour a plantation and factory, and stay in a colonial-era hill station where the evenings are cool.', ['Nuwara Eliya'], ['Guided Tea Plantation and Factory Tour'], ['Kandy', 'Nuwara Eliya', 78, 'VAN'], [1, 1, 1], 3],
      ['Bentota Beach and Departure', 'Descend to the coast for a morning on the sand and a Madu River boat safari through mangrove tunnels before the airport transfer.', ['Bentota'], ['Madu River boat safari'], ['Nuwara Eliya', 'Bentota', 210, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'yala-udawalawe-safari-trail',
    title: 'Yala & Udawalawe Wildlife Safari Trail',
    dest: 'sriLanka',
    category: 'WILD_SAFARI',
    days: 5,
    basePrice: 1290,
    marginType: 'PERCENTAGE',
    marginInput: 20,
    featured: true,
    rating: 4.8,
    views: 596,
    bookings: 17,
    inclusions: ['4 nights in safari lodges', 'All meals on safari days', 'Private 4x4 with tracker for every park entry', 'Park permits and conservancy fees', 'Airport transfers'],
    exclusions: ['International flights', 'Alcoholic beverages', 'Travel insurance', 'Tips for trackers and drivers'],
    terms: 'Peak season (December to March) requires full payment 30 days ahead. Park fees are non-refundable once permits are issued.',
    cover: 'https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival and Negombo Lagoon', 'Arrive and rest at the coast. Late-afternoon lagoon boat ride with good birding before an early night ahead of the safari circuit.', ['Negombo'], ['Airport Meet and Greet'], ['Colombo', 'Negombo', 12, 'VAN'], [0, 0, 1], 0],
      ['Drive to Udawalawe and Afternoon Safari', 'Cross the island to Udawalawe, the best place in Sri Lanka to see wild elephants at close range, for a late-afternoon game drive.', ['Udawalawe', 'Yala'], ['Yala National Park jeep safari'], ['Negombo', 'Udawalawe', 230, 'VAN'], [1, 1, 1], 4],
      ['Full Day in Yala National Park', 'Dawn and afternoon game drives in Yala Block 1, tracking leopard, sloth bear and elephant with your own tracker.', ['Yala'], ['Yala National Park jeep safari'], ['Yala', 'Yala', 24, 'CAR'], [1, 1, 1], 4],
      ['Bundala Birds and Coastal Afternoon', 'Morning birding in Bundala\u2019s wetlands, a Ramsar site with thousands of migratory shorebirds, then time on the beach.', ['Yala', 'Bentota'], ['Stilt fishing photo stop'], ['Yala', 'Bentota', 165, 'VAN'], [1, 1, 1], 5],
      ['Mirissa Whale Watching and Departure', 'Early morning whale and dolphin cruise from Mirissa, then the expressway back to the airport.', ['Mirissa'], ['Morning whale and dolphin watching cruise'], ['Bentota', 'Mirissa', 62, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'maldives-overwater-villa-romance',
    title: 'Maldives Overwater Villa Romance',
    dest: 'maldives',
    category: 'HONEYMOON',
    days: 5,
    basePrice: 3480,
    marginType: 'PERCENTAGE',
    marginInput: 18,
    featured: true,
    rating: 4.9,
    views: 1124,
    bookings: 16,
    inclusions: ['4 nights in an overwater villa', 'Half-board dining', 'Return seaplane or speedboat transfers', 'Snorkeling equipment', 'Honeymoon turndown and fruit basket'],
    exclusions: ['International flights to Mal\u00e9', 'Alcoholic beverages and premium dining', 'Spa treatments', 'Scuba diving and excursions'],
    terms: 'Non-refundable within 30 days of check-in. Honeymoon rate requires a marriage certificate dated within 12 months.',
    cover: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Mal\u00e9 and Transfer to the Atoll', 'Meet and greet at Velana International, then the seaplane hop over the atolls to your island resort. Sunset cocktails on the deck.', ['Mal\u00e9', 'North Mal\u00e9 Atoll'], ['Seaplane transfer to resort'], ['Mal\u00e9', 'North Mal\u00e9 Atoll', 60, 'FLIGHT'], [0, 0, 1], 0],
      ['House Reef and Couples Spa', 'Guided house-reef snorkeling in the morning, then an overwater couples spa ritual in the afternoon.', ['North Mal\u00e9 Atoll'], ['Guided house-reef snorkeling', 'Couples spa ritual'], null, [1, 1, 1], 0],
      ['Sandbank Picnic and Sunset Cruise', 'Private sandbank picnic with a chilled hamper, followed by a dolphin-watching sunset cruise.', ['North Mal\u00e9 Atoll'], ['Sandbank picnic', 'Sunset dolphin cruise'], null, [1, 1, 1], 0],
      ['Manta Rays and Overwater Dinner', 'Morning excursion to a cleaning station for manta rays, then a private overwater dinner under lanterns.', ['North Mal\u00e9 Atoll'], ['Manta ray and whale shark excursion', 'Overwater dinner experience'], null, [1, 1, 1], 0],
      ['Final Morning and Departure', 'Late breakfast, a last swim off the villa deck, then the seaplane transfer back to Mal\u00e9 for your onward flight.', ['Mal\u00e9'], ['Seaplane transfer to resort'], ['North Mal\u00e9 Atoll', 'Mal\u00e9', 60, 'FLIGHT'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'thailand-island-hopper',
    title: 'Thailand Island Hopper',
    dest: 'thailand',
    category: 'COUPLE',
    days: 7,
    basePrice: 1440,
    marginType: 'PERCENTAGE',
    marginInput: 22,
    featured: true,
    rating: 4.7,
    views: 874,
    bookings: 19,
    inclusions: ['6 nights in boutique hotels', 'Daily breakfast', 'Domestic flights Bangkok\u2013Krabi\u2013Bangkok', 'Speedboat island-hopping tour', 'All airport and pier transfers'],
    exclusions: ['International flights', 'Lunches and dinners unless listed', 'National park entry fees on some islands', 'Travel insurance and gratuities'],
    terms: '20% deposit confirms the booking; balance 30 days before departure. Peak season surcharge applies 20 Dec to 10 Jan.',
    cover: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Bangkok', 'Arrive at Suvarnabhumi and transfer to a riverside hotel. Evening rooftop dinner overlooking the Chao Phraya.', ['Bangkok'], ['Airport Meet and Greet'], ['Bangkok', 'Bangkok', 30, 'VAN'], [0, 0, 1], 0],
      ['Grand Palace and Chao Phraya', 'Guided tour of the Grand Palace and Wat Pho, then a longtail boat through the canals and a dinner cruise.', ['Bangkok'], ['Grand Palace tour', 'Chao Phraya dinner cruise'], null, [1, 1, 1], 0],
      ['Floating Market and Fly to the Coast', 'Early visit to the Damnoen Saduak floating market, then fly south and transfer to your beach hotel.', ['Damnoen Saduak', 'Krabi'], ['Floating market visit'], ['Bangkok', 'Krabi', 810, 'FLIGHT'], [1, 0, 1], 4],
      ['Phi Phi Island Hopping', 'Full-day speedboat tour through Maya Bay, Pileh Lagoon and Bamboo Island with snorkeling stops.', ['Phi Phi Islands'], ['Phi Phi island-hopping by speedboat'], ['Krabi', 'Phi Phi Islands', 46, 'BOAT'], [1, 1, 0], 4],
      ['James Bond Island and Sea Kayaking', 'Canoe through the limestone caves of Phang Nga Bay and visit the famous James Bond Island.', ['Krabi'], ['James Bond Island canoe tour'], null, [1, 1, 0], 4],
      ['Railay Beach and Thai Massage', 'Free morning on Railay\u2019s cliffs, afternoon traditional Thai massage, and a beachside seafood dinner.', ['Krabi'], ['Traditional Thai massage'], null, [1, 0, 1], 4],
      ['Fly to Bangkok and Depart', 'Morning flight back to Bangkok for onward connections, with time for last-minute shopping at the airport.', ['Bangkok'], [], ['Krabi', 'Bangkok', 810, 'FLIGHT'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'bangkok-chiang-mai-family-explorer',
    title: 'Bangkok & Chiang Mai Family Explorer',
    dest: 'thailand',
    category: 'FAMILY',
    days: 6,
    basePrice: 1220,
    marginType: 'PERCENTAGE',
    marginInput: 20,
    featured: false,
    rating: 4.5,
    views: 331,
    bookings: 11,
    inclusions: ['5 nights in family rooms', 'Daily breakfast', 'Domestic flight Bangkok\u2013Chiang Mai', 'Elephant sanctuary day visit', 'Private transfers throughout'],
    exclusions: ['International flights', 'Most lunches and dinners', 'Travel insurance', 'Optional adventure activities'],
    terms: 'Deposit 25% on booking; balance 21 days before travel. Child rates apply under 12 sharing with two adults.',
    cover: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Bangkok', 'Arrive and transfer to your hotel. Evening at Asiatique riverfront with dinner and a Ferris wheel ride for the kids.', ['Bangkok'], ['Airport Meet and Greet'], ['Bangkok', 'Bangkok', 30, 'VAN'], [0, 0, 1], 0],
      ['Grand Palace and Canal Adventure', 'Royal palaces and Wat Pho in the morning, then a longtail boat ride through the canal network with a stop at a riverside temple.', ['Bangkok'], ['Grand Palace tour'], null, [1, 1, 1], 0],
      ['Fly North to Chiang Mai', 'Morning flight to Chiang Mai. Afternoon at the Night Bazaar and a family-friendly Khantoke dinner with traditional dance.', ['Chiang Mai'], ['Night bazaar walk'], ['Bangkok', 'Chiang Mai', 580, 'FLIGHT'], [1, 0, 1], 2],
      ['Ethical Elephant Sanctuary', 'A full day at a sanctuary that rescues working elephants — feeding, mud baths and walking with them, with a vegetarian lunch.', ['Chiang Mai'], ['Ethical elephant sanctuary visit'], ['Chiang Mai', 'Chiang Mai', 60, 'VAN'], [1, 1, 1], 2],
      ['Doi Suthep and Thai Cooking', 'Morning at the mountain temple of Doi Suthep, then a hands-on cooking class where everyone makes their own pad thai.', ['Chiang Mai'], ['Doi Suthep temple visit', 'Thai cooking class'], null, [1, 1, 1], 2],
      ['Departure', 'Free morning for last shopping in the old city before the transfer to Chiang Mai airport.', ['Chiang Mai'], [], ['Chiang Mai', 'Chiang Mai', 12, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'bali-island-discovery',
    title: 'Bali Island Discovery',
    dest: 'bali',
    category: 'FAMILY',
    days: 8,
    basePrice: 1690,
    marginType: 'PERCENTAGE',
    marginInput: 21,
    featured: true,
    rating: 4.8,
    views: 1042,
    bookings: 24,
    inclusions: ['7 nights across Ubud and Seminyak', 'Daily breakfast', 'Private car with driver-guide each day', 'Mount Batur sunrise trek', 'Airport transfers'],
    exclusions: ['International flights', 'Lunches and dinners unless listed', 'Spa treatments', 'Bali tourist levy (paid on arrival)'],
    terms: '30% deposit to confirm; balance due 30 days before arrival. Free cancellation up to 45 days before check-in.',
    cover: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Denpasar', 'Met at Ngurah Rai and transferred to Ubud, the island\u2019s cultural heart. Evening walk through the rice fields.', ['Ubud'], ['Airport Meet and Greet'], ['Ubud', 'Ubud', 42, 'VAN'], [0, 0, 1], 0],
      ['Ubud Highlights', 'Tegallalang rice terraces, the Sacred Monkey Forest and a purification ritual at Tirta Empul spring temple.', ['Tegallalang', 'Ubud', 'Tirta Empul'], ['Tegallalang rice terrace walk', 'Ubud Monkey Forest visit', 'Tirta Empul purification ritual'], ['Ubud', 'Tegallalang', 14, 'CAR'], [1, 1, 1], 0],
      ['Mount Batur Sunrise Trek', 'Pre-dawn ascent of Mount Batur for sunrise above the clouds, returning for a late breakfast and an afternoon at leisure.', ['Kintamani', 'Ubud'], ['Mount Batur sunrise trek'], ['Ubud', 'Kintamani', 38, 'CAR'], [1, 0, 1], 0],
      ['Balinese Cooking and Crafts', 'Morning market visit and a family cooking class, then a silver-smithing workshop in the village of Celuk.', ['Ubud'], ['Balinese cooking class', 'Silver-smithing workshop'], null, [1, 1, 0], 0],
      ['Nusa Penida Day Trip', 'Speedboat to Nusa Penida for Kelingking Beach, Angel\u2019s Billabong and snorkeling with manta rays.', ['Nusa Penida'], ['Nusa Penida island day trip', 'Kelingking Beach viewpoint'], ['Ubud', 'Nusa Penida', 32, 'BOAT'], [1, 1, 0], 0],
      ['Move to Seminyak and Uluwatu Sunset', 'Transfer to the beach side of the island; evening at Uluwatu Temple with the Kecak fire dance at sunset.', ['Seminyak', 'Uluwatu'], ['Uluwatu Temple sunset & Kecak dance'], ['Ubud', 'Seminyak', 34, 'VAN'], [1, 0, 1], 2],
      ['Beach Day and Ayung Rafting', 'Choose a lazy beach morning or white-water rafting on the Ayung river, then a Jimbaran seafood dinner on the sand.', ['Seminyak'], ['White-water rafting on the Ayung', 'Jimbaran seafood beach dinner'], null, [1, 0, 1], 2],
      ['Departure', 'Late morning checkout and transfer to the airport for your flight home.', ['Seminyak'], [], ['Seminyak', 'Seminyak', 18, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'dubai-family-theme-park-adventure',
    title: 'Dubai Family Theme Park Adventure',
    dest: 'uae',
    category: 'FAMILY',
    days: 6,
    basePrice: 1980,
    marginType: 'PERCENTAGE',
    marginInput: 25,
    featured: true,
    rating: 4.6,
    views: 688,
    bookings: 15,
    inclusions: ['5 nights in a family suite', 'Daily breakfast', 'Three theme park tickets', 'Desert safari with dinner', 'Private airport transfers'],
    exclusions: ['International flights', 'Lunches and dinners unless listed', 'Ski Dubai and optional add-ons', 'Tourism Dirham city tax paid at hotel'],
    terms: 'Full payment required 30 days before arrival. Theme park tickets are date-specific and non-refundable once issued.',
    cover: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Dubai', 'Arrive at DXB and transfer to the marina. Evening at the Dubai Fountain show and a stroll through Downtown.', ['Downtown Dubai'], ['Airport Meet and Greet', 'Dubai Fountain show'], ['Dubai', 'Downtown Dubai', 20, 'VAN'], [0, 0, 1], 3],
      ['Burj Khalifa and Dubai Mall', 'Skip-the-line access to the Burj Khalifa observation deck, then the Dubai Aquarium and the world\u2019s largest mall.', ['Downtown Dubai', 'Old Dubai'], ['Burj Khalifa observation deck', 'Dubai Mall & aquarium visit'], null, [1, 1, 0], 3],
      ['Desert Safari and Camel Ride', 'Afternoon dune bashing in the red dunes, camel rides and sandboarding, followed by a barbecue dinner with live entertainment.', ['Dubai Desert'], ['Desert safari with BBQ dinner', 'Dune bashing', 'Camel ride'], ['Downtown Dubai', 'Dubai Desert', 65, 'CAR'], [1, 0, 1], 3],
      ['Ferrari World Abu Dhabi', 'Day trip to Abu Dhabi for the world\u2019s fastest roller coaster, then the Sheikh Zayed Grand Mosque before returning.', ['Abu Dhabi'], ['Ferrari World Abu Dhabi', 'Sheikh Zayed Grand Mosque visit'], ['Dubai', 'Abu Dhabi', 140, 'VAN'], [1, 1, 0], 3],
      ['Palm Jumeirah and Old Dubai', 'Morning on the Palm with a cable car ride, afternoon in the gold and spice souks and crossing the creek by abra.', ['Palm Jumeirah', 'Old Dubai'], ['Dubai Creek abra ride', 'Gold and spice souk walk'], null, [1, 1, 1], 3],
      ['Departure', 'Free morning for shopping before the transfer to Dubai International Airport.', ['Downtown Dubai'], [], ['Downtown Dubai', 'Dubai', 20, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'abu-dhabi-dubai-city-break',
    title: 'Abu Dhabi & Dubai City Break',
    dest: 'uae',
    category: 'COUPLE',
    days: 4,
    basePrice: 1240,
    marginType: 'PERCENTAGE',
    marginInput: 26,
    featured: false,
    rating: 4.5,
    views: 297,
    bookings: 9,
    inclusions: ['3 nights in a five-star hotel', 'Daily breakfast', 'Museum of the Future entry', 'Desert dinner experience', 'Inter-emirate transfers'],
    exclusions: ['International flights', 'Dinners other than the desert experience', 'Alcohol', 'Travel insurance'],
    terms: 'Full payment 21 days before arrival. Weekday check-in recommended for museum access.',
    cover: 'https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival and Museum of the Future', 'Arrive and check in, then take in the Museum of the Future \u2014 the building Dubai will be remembered for.', ['Downtown Dubai'], ['Airport Meet and Greet', 'Museum of the Future'], ['Dubai', 'Downtown Dubai', 20, 'VAN'], [0, 0, 1], 3],
      ['Old Dubai and Creek Crossings', 'Textile and spice souks, a creek crossing by abra and lunch at a heritage house before an evening dhow cruise.', ['Old Dubai'], ['Dubai Creek abra ride', 'Gold and spice souk walk', 'Dubai Marina dhow cruise dinner'], null, [1, 1, 1], 3],
      ['Abu Dhabi: Louvre and Grand Mosque', 'Drive to the capital for the Louvre Abu Dhabi and the Sheikh Zayed Grand Mosque, returning in the evening.', ['Abu Dhabi'], ['Sheikh Zayed Grand Mosque visit'], ['Dubai', 'Abu Dhabi', 140, 'VAN'], [1, 1, 0], 3],
      ['Desert Morning and Departure', 'Sunrise in the dunes with breakfast at a desert camp before the transfer back to the airport.', ['Dubai Desert'], ['Dune bashing'], ['Abu Dhabi', 'Dubai Desert', 180, 'CAR'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'japan-cherry-blossom-trail',
    title: 'Japan Cherry Blossom Trail',
    dest: 'japan',
    category: 'COUPLE',
    days: 10,
    basePrice: 4260,
    marginType: 'PERCENTAGE',
    marginInput: 17,
    featured: true,
    rating: 4.9,
    views: 1310,
    bookings: 12,
    inclusions: ['9 nights in central hotels', '7-day Japan Rail Pass', 'Daily breakfast and two dinners', 'All guided experiences listed', 'Airport transfers'],
    exclusions: ['International flights', 'Most lunches and dinners', 'Onsen and spa fees', 'Travel insurance and personal shopping'],
    terms: 'Sakura season dates cannot be guaranteed. Full payment 45 days before departure; 50% cancellation charge inside 21 days.',
    cover: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Tokyo', 'Arrive at Narita and transfer into the city. Evening walk through Shinjuku\u2019s neon canyons with dinner at an izakaya.', ['Tokyo'], ['Airport Meet and Greet', 'Shibuya Crossing walk'], ['Tokyo', 'Tokyo', 70, 'VAN'], [0, 0, 1], 0],
      ['Tokyo Icons and Markets', 'Meiji Shrine at dawn, the Tsukiji outer market for breakfast, then Akihabara and the Nakamise shopping street at Asakusa.', ['Tokyo', 'Asakusa'], ['Meiji Shrine visit', 'Tsukiji Outer Market breakfast tour'], null, [1, 1, 0], 0],
      ['Mt Fuji and Hakone Onsen', 'Lake Ashi cruise and the Hakone Ropeway with views of Fuji, staying overnight in a ryokan with a hot-spring bath and kaiseki dinner.', ['Mt Fuji', 'Hakone'], ['Mt Fuji and Lake Ashi day trip', 'Onsen ryokan experience'], ['Tokyo', 'Hakone', 95, 'TRAIN'], [1, 0, 1], 2],
      ['Bullet Train to Kyoto', 'Shinkansen south to Kyoto. Afternoon in the Gion geisha district and an evening walk along the Pontocho alley.', ['Kyoto', 'Gion'], ['JR Pass activation and rail travel', 'Gion geisha district evening walk'], ['Hakone', 'Kyoto', 400, 'TRAIN'], [1, 0, 1], 1],
      ['Kyoto Temples in Bloom', 'Fushimi Inari\u2019s thousand torii gates at first light, then the Golden Pavilion and the Arashiyama bamboo grove.', ['Kyoto', 'Fushimi', 'Arashiyama'], ['Fushimi Inari shrine walk', 'Kinkaku-ji Golden Pavilion', 'Arashiyama Bamboo Grove visit'], ['Kyoto', 'Kyoto', 24, 'CAR'], [1, 1, 1], 1],
      ['Nara and Tea Ceremony', 'Day trip to Nara for the deer park and Todaiji temple, returning for a formal tea ceremony in Kyoto.', ['Nara', 'Kyoto'], ['Nara deer park day trip', 'Traditional tea ceremony'], ['Kyoto', 'Nara', 45, 'TRAIN'], [1, 1, 0], 1],
      ['Osaka Street Food and Castle', 'Train to Osaka, the castle and its moat, then an evening food crawl through Dotonbori and Kuromon market.', ['Osaka'], ['Osaka Castle visit', 'Dotonbori food crawl'], ['Kyoto', 'Osaka', 45, 'TRAIN'], [1, 1, 1], 3],
      ['Hiroshima and Miyajima', 'Shinkansen west to Hiroshima for the Peace Memorial, then the ferry to Miyajima and the floating torii gate.', ['Hiroshima', 'Miyajima'], ['Hiroshima Peace Memorial', 'Miyajima ferry and Itsukushima Shrine'], ['Osaka', 'Hiroshima', 340, 'TRAIN'], [1, 1, 1], 3],
      ['Hanami in the Parks', 'A slow day: cherry blossoms in Osaka\u2019s parks, last-minute shopping and a farewell dinner.', ['Osaka'], ['Nishiki Market'], null, [1, 0, 1], 3],
      ['Departure from Kansai', 'Transfer to Kansai International Airport for the flight home.', ['Osaka'], [], ['Osaka', 'Osaka', 50, 'TRAIN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'singapore-sentosa-family-fun',
    title: 'Singapore & Sentosa Family Fun',
    dest: 'singapore',
    category: 'FAMILY',
    days: 5,
    basePrice: 1320,
    marginType: 'PERCENTAGE',
    marginInput: 22,
    featured: false,
    rating: 4.6,
    views: 384,
    bookings: 13,
    inclusions: ['4 nights on Sentosa', 'Daily breakfast', 'Universal Studios and S.E.A. Aquarium tickets', 'Night Safari with tram ride', 'All transfers'],
    exclusions: ['International flights', 'Lunches and dinners', 'Travel insurance', 'Optional cable car rides'],
    terms: 'Deposit 30% on booking, balance 30 days before arrival. Attraction tickets are non-refundable once issued.',
    cover: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival and Marina Bay', 'Arrive at Changi and transfer to Sentosa. Evening at Gardens by the Bay for the Supertree light show.', ['Marina Bay', 'Sentosa'], ['Airport Meet and Greet', 'Gardens by the Bay & Supertree show'], ['Sentosa', 'Marina Bay', 14, 'VAN'], [0, 0, 1], 1],
      ['Universal Studios Singapore', 'A full day in the park \u2014 Battlestar Galactica, the Transformers ride and the water world stunt show.', ['Sentosa'], ['Universal Studios Singapore'], null, [1, 1, 0], 1],
      ['S.E.A. Aquarium and Beaches', 'Morning at the aquarium, then the Sentosa beaches and a cable car ride across the harbour.', ['Sentosa'], ['S.E.A. Aquarium', 'Sentosa cable car ride'], null, [1, 1, 1], 1],
      ['Singapore Zoo and Night Safari', 'Breakfast with the orangutans at the zoo, then the Night Safari after dark for the nocturnal animals.', ['Mandai'], ['Singapore Zoo with breakfast in the wild', 'Night Safari'], ['Sentosa', 'Mandai', 28, 'VAN'], [1, 1, 0], 1],
      ['Hawker Trail and Departure', 'Morning hawker food trail through Chinatown and Kampong Glam, then transfer to Changi for the flight home.', ['Chinatown', 'Kampong Glam'], ['Hawker food trail with a guide'], ['Sentosa', 'Chinatown', 10, 'VAN'], [1, 1, 0], -1],
    ]),
  },
  {
    key: 'vietnam-family-explorer',
    title: 'Vietnam Family Explorer',
    dest: 'vietnam',
    category: 'FAMILY',
    days: 9,
    basePrice: 1470,
    marginType: 'PERCENTAGE',
    marginInput: 24,
    featured: true,
    rating: 4.7,
    views: 526,
    bookings: 14,
    inclusions: ['8 nights in family rooms', 'Daily breakfast and four dinners', 'Internal flights Hanoi\u2013Da Nang\u2013Ho Chi Minh City', 'Ha Long Bay overnight cruise', 'All transfers'],
    exclusions: ['International flights', 'Vietnam e-visa fee', 'Lunches and remaining dinners', 'Travel insurance and tips'],
    terms: '25% deposit on booking; balance 30 days before travel. Ha Long cruises may be rerouted in bad weather.',
    cover: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Hanoi', 'Arrive in the capital and settle into the Old Quarter. Evening street-food walk with the family.', ['Hanoi'], ['Airport Meet and Greet', 'Old Quarter street food walk'], ['Hanoi', 'Hanoi', 35, 'VAN'], [0, 0, 1], 0],
      ['Hanoi and Water Puppets', 'Ho Chi Minh\u2019s mausoleum and the Temple of Literature, then a water puppet performance in the evening.', ['Hanoi'], ['Water puppet theatre'], null, [1, 1, 0], 0],
      ['Ha Long Bay Overnight Cruise', 'Drive to the coast and board your junk for an overnight cruise among the limestone karsts, with kayaking and a cave visit.', ['Ha Long Bay'], ['Ha Long Bay overnight cruise'], ['Hanoi', 'Ha Long Bay', 160, 'VAN'], [1, 1, 1], 3],
      ['Fly to Da Nang and Hoi An', 'Morning tai chi on deck, then back to Hanoi for the flight south. Evening in lantern-lit Hoi An.', ['Hoi An', 'Da Nang'], ['Hoi An Ancient Town lantern walk'], ['Hanoi', 'Da Nang', 630, 'FLIGHT'], [1, 0, 1], 1],
      ['Hoi An Cooking and Tailoring', 'Morning cooking class in a garden by the river, afternoon tailoring fittings and free time on An Bang beach.', ['Hoi An'], ['Cooking class in a Hoi An garden', 'Tailor fitting in Hoi An'], null, [1, 0, 1], 1],
      ['Hai Van Pass and Hue', 'Cross the Hai Van Pass to the imperial city of Hue for the Citadel and the tombs along the Perfume River.', ['Hue'], ['Hue Imperial Citadel tour', 'Hai Van Pass motorbike ride'], ['Hoi An', 'Hue', 125, 'VAN'], [1, 1, 1], 1],
      ['Fly to Ho Chi Minh City', 'Flight south to Saigon. Afternoon at the War Remnants Museum and a sunset walk along Nguyen Hue.', ['Ho Chi Minh City'], ['Airport Meet and Greet'], ['Hue', 'Ho Chi Minh City', 960, 'FLIGHT'], [1, 0, 1], 2],
      ['Mekong Delta and Cu Chi', 'Full day to the Mekong Delta for boat rides and bicycle lanes through the villages, returning via the Cu Chi tunnels.', ['Can Tho'], ['Mekong Delta boat and bicycle tour', 'Cu Chi Tunnels guided visit'], ['Ho Chi Minh City', 'Can Tho', 170, 'VAN'], [1, 1, 0], 2],
      ['Departure', 'Free morning in the city before the transfer to Tan Son Nhat for the flight home.', ['Ho Chi Minh City'], [], ['Ho Chi Minh City', 'Ho Chi Minh City', 8, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'nepal-everest-view-trek',
    title: 'Nepal Everest View Trek',
    dest: 'nepal',
    category: 'GROUP',
    days: 11,
    basePrice: 1820,
    marginType: 'FIXED',
    marginInput: 420,
    featured: true,
    rating: 4.8,
    views: 742,
    bookings: 10,
    inclusions: ['10 nights in lodges and hotels', 'All meals on trekking days', 'Licensed English-speaking trekking guide', 'Lukla flights and all permits', 'Porter support (one per two trekkers)'],
    exclusions: ['International flights to Kathmandu', 'Nepal visa fee', 'Travel and evacuation insurance (mandatory)', 'Personal trekking gear and tips'],
    terms: 'Departures are fixed and weather-dependent. Full payment 45 days before departure; Lukla flights are non-refundable.',
    cover: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Kathmandu', 'Arrive in Kathmandu and meet the trekking team. Evening briefing over a traditional Nepali dinner.', ['Kathmandu'], ['Airport Meet and Greet'], ['Kathmandu', 'Kathmandu', 7, 'CAR'], [0, 0, 1], 0],
      ['Kathmandu Valley Sightseeing', 'Boudhanath Stupa, Pashupatinath and the old royal square at Bhaktapur, with time to buy any missing gear.', ['Kathmandu', 'Bhaktapur'], ['Boudhanath Stupa kora walk', 'Pashupatinath Temple visit', 'Bhaktapur old city walk'], ['Kathmandu', 'Bhaktapur', 14, 'CAR'], [1, 1, 1], 0],
      ['Fly to Lukla and Trek to Phakding', 'The famous mountain flight into Lukla, then an easy first day descending to the Dudh Koshi river.', ['Lukla', 'Phakding'], ['Momo cooking class'], ['Kathmandu', 'Lukla', 140, 'FLIGHT'], [1, 1, 1], 2],
      ['Trek to Namche Bazaar', 'Cross the high suspension bridges of the Dudh Koshi and climb to Namche, the Sherpa capital.', ['Namche Bazaar'], [], null, [1, 1, 1], 2],
      ['Acclimatisation Day in Namche', 'A rest day to acclimatise: a short hike to the Everest View Hotel for the first sight of the peak, then the Sherpa museum.', ['Namche Bazaar'], ['Everest scenic mountain flight'], null, [1, 1, 1], 2],
      ['Trek to Tengboche Monastery', 'Traverse the hillside above the Dudh Koshi with Everest, Lhotse and Ama Dablam ahead, and stay beside the region\u2019s great monastery.', ['Tengboche'], ['Trek to Tengboche Monastery'], ['Namche Bazaar', 'Tengboche', 12, 'CAR'], [1, 1, 1], 3],
      ['Tengboche to Khumjung', 'Descend through rhododendron forest to the village of Khumjung, home of the famous school and the yeti scalp relic.', ['Khumjung'], [], null, [1, 1, 1], 2],
      ['Return to Namche and Phakding', 'A long descent back down the valley, retracing the bridges to Phakding.', ['Namche Bazaar', 'Phakding'], [], null, [1, 1, 1], 2],
      ['Trek to Lukla', 'Final trekking day, climbing back to Lukla for a celebratory dinner with the crew.', ['Lukla'], [], null, [1, 1, 1], 2],
      ['Fly to Kathmandu', 'Morning flight out of the mountains, afternoon at leisure and a farewell dinner in Thamel.', ['Kathmandu'], ['Boudhanath Stupa kora walk'], ['Lukla', 'Kathmandu', 140, 'FLIGHT'], [1, 0, 1], 0],
      ['Departure', 'Transfer to Tribhuvan International Airport for the flight home.', ['Kathmandu'], [], ['Kathmandu', 'Kathmandu', 7, 'CAR'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'turkey-istanbul-cappadocia',
    title: 'Turkey Highlights: Istanbul & Cappadocia',
    dest: 'turkey',
    category: 'GROUP',
    days: 9,
    basePrice: 1560,
    marginType: 'PERCENTAGE',
    marginInput: 23,
    featured: true,
    rating: 4.7,
    views: 468,
    bookings: 12,
    inclusions: ['8 nights in boutique and cave hotels', 'Daily breakfast and four dinners', 'Domestic flight Istanbul\u2013Cappadocia', 'Guided touring throughout', 'All museum entries listed'],
    exclusions: ['International flights', 'Hot-air balloon flight', 'Lunches', 'Turkish bath and personal expenses'],
    terms: '30% deposit on booking, balance 30 days before departure. Balloon flights are weather-dependent and refunded if cancelled.',
    cover: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Istanbul', 'Arrive at Istanbul Airport and transfer to the old city. Evening at leisure around Sultanahmet.', ['Istanbul'], ['Airport Meet and Greet'], ['Istanbul', 'Istanbul', 45, 'VAN'], [0, 0, 1], 0],
      ['Hagia Sophia and the Grand Bazaar', 'Imperial Istanbul: Hagia Sophia, the Blue Mosque and Topkapi Palace, then the labyrinth of the Grand Bazaar.', ['Istanbul'], ['Hagia Sophia and Blue Mosque visit', 'Topkapi Palace tour', 'Grand Bazaar walk with a guide'], null, [1, 1, 1], 0],
      ['Bosphorus and the Spice Market', 'Morning at the Spice Bazaar and a Bosphorus cruise between two continents, with an evening hamam experience.', ['Istanbul'], ['Bosphorus dinner cruise', 'Turkish bath (hamam) experience'], null, [1, 1, 1], 0],
      ['Fly to Cappadocia', 'Morning flight to Kayseri and transfer to your cave hotel in Goreme. Afternoon walk through the fairy chimneys.', ['Cappadocia'], ['Goreme Open Air Museum'], ['Istanbul', 'Cappadocia', 730, 'FLIGHT'], [1, 0, 1], 1],
      ['Balloon Flight and Underground Cities', 'Sunrise hot-air balloon flight over the valleys, then the underground city of Kaymakli and the Uchisar castle.', ['Cappadocia'], ['Cappadocia hot-air balloon flight', 'Underground city of Kaymakli'], null, [1, 1, 1], 1],
      ['Drive to Konya and Pamukkale', 'Long scenic drive across the Anatolian plateau via Konya\u2019s Mevlana museum to the white terraces of Pamukkale.', ['Pamukkale'], ['Pamukkale travertines and Hierapolis'], ['Cappadocia', 'Pamukkale', 640, 'VAN'], [1, 1, 1], 3],
      ['Ephesus and Ku\u015fadas\u0131', 'The best-preserved ancient city in the Mediterranean, then the Aegean coast at Ku\u015fadas\u0131.', ['Ephesus', 'Ku\u015fadas\u0131'], ['Ephesus ancient city tour'], ['Pamukkale', 'Ku\u015fadas\u0131', 250, 'VAN'], [1, 1, 1], 2],
      ['Whirling Dervishes and Free Day', 'A slower day on the coast with an evening whirling dervish ceremony, or an optional cooking class.', ['Ku\u015fadas\u0131'], ['Whirling dervish ceremony', 'Turkish cooking class'], null, [1, 0, 1], 2],
      ['Return to Istanbul and Departure', 'Fly back to Istanbul for onward international connections.', ['Istanbul'], [], ['Ku\u015fadas\u0131', 'Istanbul', 570, 'FLIGHT'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'egypt-nile-cruise-pyramids',
    title: 'Egypt Nile Cruise & Pyramids',
    dest: 'egypt',
    category: 'GROUP',
    days: 8,
    basePrice: 1680,
    marginType: 'PERCENTAGE',
    marginInput: 22,
    featured: true,
    rating: 4.8,
    views: 612,
    bookings: 13,
    inclusions: ['3 nights in Cairo, 4 nights on a Nile cruise', 'Daily breakfast and full board on the cruise', 'Domestic flights Cairo\u2013Aswan and Luxor\u2013Cairo', 'Egyptologist guide throughout', 'All monument entries listed'],
    exclusions: ['International flights', 'Egypt visa (on arrival)', 'Abu Simbel day trip', 'Drinks, tips and personal expenses'],
    terms: '25% deposit on booking, balance 35 days before travel. Nile cruise cabins are allocated on embarkation.',
    cover: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Cairo', 'Arrive at Cairo International and transfer to a hotel with pyramid views. Evening sound-and-light show at Giza.', ['Cairo', 'Giza'], ['Airport Meet and Greet', 'Sound and light show at Karnak'], ['Cairo', 'Giza', 25, 'VAN'], [0, 0, 1], 0],
      ['Pyramids, Sphinx and the Grand Museum', 'Morning at the Pyramids of Giza and the Sphinx, then the Grand Egyptian Museum and its Tutankhamun galleries.', ['Giza', 'Cairo'], ['Pyramids of Giza and Sphinx tour', 'Grand Egyptian Museum entry'], null, [1, 1, 1], 0],
      ['Old Cairo and Khan el-Khalili', 'The Egyptian Museum, the Hanging Church and the bazaar of Khan el-Khalili with coffee at El Fishawy.', ['Cairo'], ['Egyptian Museum guided visit', 'Khan el-Khalili bazaar walk'], null, [1, 1, 1], 0],
      ['Fly to Aswan and Board the Cruise', 'Fly south to Aswan for the Philae temple and a felucca sail before boarding your Nile cruise.', ['Aswan'], ['Nile felucca sail at sunset'], ['Cairo', 'Aswan', 680, 'FLIGHT'], [1, 1, 1], 1],
      ['Kom Ombo and Edfu', 'Morning at the double temple of Kom Ombo, then Edfu\u2019s Horus temple as the ship sails north.', ['Kom Ombo', 'Edfu'], ['Nubian village visit'], ['Aswan', 'Kom Ombo', 50, 'BOAT'], [1, 1, 1], 1],
      ['Luxor: Karnak and the Temples', 'Disembark in Luxor for the vast Karnak complex and Luxor Temple, with an optional hot-air balloon at dawn.', ['Luxor'], ['Karnak and Luxor Temple tour', 'Hot-air balloon over Luxor'], ['Edfu', 'Luxor', 105, 'BOAT'], [1, 1, 1], 2],
      ['Valley of the Kings and Hatshepsut', 'Cross to the west bank for the Valley of the Kings, the temple of Hatshepsut and the Colossi of Memnon.', ['Luxor'], ['Valley of the Kings with Tutankhamun tomb'], null, [1, 1, 1], 2],
      ['Fly to Cairo and Departure', 'Morning flight back to Cairo for onward international departures.', ['Cairo'], [], ['Luxor', 'Cairo', 500, 'FLIGHT'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'morocco-imperial-cities',
    title: 'Morocco Imperial Cities',
    dest: 'morocco',
    category: 'COUPLE',
    days: 8,
    basePrice: 1520,
    marginType: 'PERCENTAGE',
    marginInput: 24,
    featured: false,
    rating: 4.6,
    views: 358,
    bookings: 9,
    inclusions: ['7 nights in riads and kasbahs', 'Daily breakfast and three dinners', 'Private car with driver-guide', 'Sahara desert camp with camel trek', 'All guided medina walks'],
    exclusions: ['International flights', 'Lunches', 'Hammam and spa treatments', 'Travel insurance and tips'],
    terms: '30% deposit on booking, balance 30 days before arrival. Desert camp subject to weather in winter months.',
    cover: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Marrakech', 'Arrive and settle into a riad inside the medina. Evening in Jemaa el-Fnaa with its storytellers and food stalls.', ['Marrakech'], ['Airport Meet and Greet', 'Jemaa el-Fnaa square evening walk'], ['Marrakech', 'Marrakech', 8, 'CAR'], [0, 0, 1], 0],
      ['Marrakech Gardens and Palaces', 'The Majorelle Garden, the Bahia Palace and the Saadian tombs, with an afternoon hammam.', ['Marrakech'], ['Majorelle Garden and Berber Museum', 'Bahia Palace tour', 'Hammam and argan oil spa'], null, [1, 1, 1], 0],
      ['Over the Atlas to A\u00eft Ben Haddou', 'Cross the Tizi n\u2019Tichka pass to the fortified kasbah of A\u00eft Ben Haddou, a UNESCO site used in countless films.', ['A\u00eft Ben Haddou', 'Ouarzazate'], ['Atlas Mountains day trip'], ['Marrakech', 'A\u00eft Ben Haddou', 180, 'VAN'], [1, 1, 1], 2],
      ['Sahara Camel Trek and Desert Camp', 'Continue to Merzouga and ride camels into the Erg Chebbi dunes for a night in a Berber camp under the stars.', ['Merzouga'], ['Sahara camel trek and desert camp'], ['A\u00eft Ben Haddou', 'Merzouga', 350, 'VAN'], [1, 1, 1], 3],
      ['Desert Sunrise and Drive to Fez', 'Sunrise over the dunes, then a long drive north through the Middle Atlas to Fez.', ['Fez'], [], ['Merzouga', 'Fez', 470, 'VAN'], [1, 1, 1], 1],
      ['Fez Medina', 'A full guided day in the world\u2019s largest car-free urban area: the tannery, the madrasas and the artisan quarters.', ['Fez'], ['Fez medina guided walk', 'Chouara leather tannery viewpoint'], null, [1, 1, 1], 1],
      ['Chefchaouen and Cooking Class', 'Day trip to the blue city in the Rif mountains, returning for a Moroccan cooking class.', ['Chefchaouen'], ['Chefchaouen blue city photo walk', 'Moroccan cooking class'], ['Fez', 'Chefchaouen', 200, 'VAN'], [1, 1, 1], 1],
      ['Departure', 'Transfer to Casablanca for the flight home, with a stop at the Hassan II Mosque.', [], [], ['Fez', 'Casablanca', 300, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'kenya-masai-mara-migration-safari',
    title: 'Kenya Masai Mara Migration Safari',
    dest: 'kenya',
    category: 'WILD_SAFARI',
    days: 7,
    basePrice: 3980,
    marginType: 'PERCENTAGE',
    marginInput: 19,
    featured: true,
    rating: 4.9,
    views: 924,
    bookings: 11,
    inclusions: ['6 nights in safari camps and lodges', 'Full board throughout', 'Private 4x4 land cruiser with a silver-level guide', 'All park and conservancy fees', 'Light-aircraft flights between parks'],
    exclusions: ['International flights', 'Kenya e-visa fee', 'Hot-air balloon safari', 'Drinks, tips and personal items'],
    terms: 'Migration crossings are a natural event and cannot be guaranteed. Full payment 60 days before departure; peak-season permits are non-refundable.',
    cover: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Arrival in Nairobi', 'Arrive at Jomo Kenyatta and transfer to a boutique hotel. Evening at the Giraffe Centre and the elephant orphanage.', ['Nairobi'], ['Airport Meet and Greet', 'Giraffe Centre and elephant orphanage'], ['Nairobi', 'Nairobi', 18, 'VAN'], [0, 0, 1], 0],
      ['Fly to the Masai Mara', 'Light-aircraft flight over the Rift Valley to the Mara. Afternoon game drive on the plains.', ['Masai Mara'], ['Maasai Mara game drive'], ['Nairobi', 'Masai Mara', 270, 'FLIGHT'], [1, 1, 1], 1],
      ['Full Day in the Mara', 'Dawn and late-afternoon game drives tracking lion prides and cheetah, returning to camp for a bush dinner.', ['Masai Mara'], ['Maasai Mara game drive', 'Great Migration river crossing viewing', 'Bush dinner under the stars'], ['Masai Mara', 'Masai Mara', 60, 'CAR'], [1, 1, 1], 1],
      ['Maasai Village and Hot-Air Balloon', 'Optional sunrise balloon safari over the plains, then a visit to a Maasai village and an afternoon drive.', ['Masai Mara'], ['Hot-air balloon safari over the Mara', 'Masai village cultural visit'], null, [1, 1, 1], 1],
      ['Fly to Lake Nakuru', 'Flight north to Lake Nakuru for flamingos, white rhino and the Rothschild giraffe in the acacia forest.', ['Lake Nakuru'], ['Lake Nakuru flamingo and rhino drive'], ['Masai Mara', 'Lake Nakuru', 240, 'FLIGHT'], [1, 1, 1], 2],
      ['Lake Naivasha and Hell\u2019s Gate', 'Boat safari past hippos on Lake Naivasha, then cycle among the wildlife of Hell\u2019s Gate.', ['Lake Naivasha'], ['Lake Naivasha boat safari', 'Hell\u2019s Gate cycling safari'], ['Lake Nakuru', 'Lake Naivasha', 90, 'VAN'], [1, 1, 1], 3],
      ['Return to Nairobi and Departure', 'Drive back to Nairobi for day rooms and the transfer to the airport for the flight home.', ['Nairobi'], [], ['Lake Naivasha', 'Nairobi', 95, 'VAN'], [1, 0, 0], -1],
    ]),
  },
  {
    key: 'bhutan-cultural-journey',
    title: 'Bhutan Cultural Journey',
    dest: 'bhutan',
    category: 'GROUP',
    days: 6,
    basePrice: 2240,
    marginType: 'FIXED',
    marginInput: 480,
    featured: false,
    rating: 4.7,
    views: 265,
    bookings: 7,
    inclusions: ['5 nights in heritage hotels', 'All meals', 'Bhutan Sustainable Development Fee', 'Private guide and vehicle throughout', 'Tiger\u2019s Nest hike with a support pony if needed'],
    exclusions: ['International flights to Paro', 'Alcohol', 'Travel insurance', 'Personal shopping and tips'],
    terms: 'The Sustainable Development Fee is payable per night and is non-refundable. Full payment 45 days before arrival.',
    cover: 'https://images.unsplash.com/photo-1553856622-d1b352e9a211?w=1200&auto=format&fit=crop&q=70',
    itinerary: F([
      ['Fly into Paro', 'One of the world\u2019s most dramatic approaches, threading between Himalayan peaks. Afternoon at Rinpung Dzong.', ['Paro'], ['Airport Meet and Greet', 'Paro Rinpung Dzong visit'], ['Paro', 'Paro', 6, 'CAR'], [0, 1, 1], 0],
      ['Thimphu, the Only Capital Without Traffic Lights', 'The Buddha Dordenma, the textile museum and the weekend market, with an evening hot-stone bath.', ['Thimphu'], ['Thimphu Buddha Dordenma viewpoint', 'National Textile Museum', 'Traditional hot-stone bath'], ['Paro', 'Thimphu', 55, 'VAN'], [1, 1, 1], 1],
      ['Dochula Pass and Punakha', 'Cross the 108 chortens of Dochula Pass to the warmer Punakha valley and its magnificent dzong at the river confluence.', ['Punakha', 'Wangdue'], ['Dochula Pass with 108 chortens', 'Punakha Dzong visit'], ['Thimphu', 'Punakha', 75, 'VAN'], [1, 1, 1], 2],
      ['Phobjikha Valley and Cooking', 'Drive to the glacial valley of Phobjikha, winter home of the black-necked crane, and learn to cook ema datshi.', ['Phobjikha'], ['Phobjikha Valley crane viewing', 'Bhutanese cooking and chilli-cheese class'], ['Punakha', 'Phobjikha', 80, 'VAN'], [1, 1, 1], 2],
      ['Back to Paro and Archery', 'Return to the Paro valley for a traditional archery lesson in local dress and free time in the town.', ['Paro'], ['Archery lesson in local dress'], ['Phobjikha', 'Paro', 190, 'VAN'], [1, 1, 1], 0],
      ['Tiger\u2019s Nest and Departure', 'The pilgrim\u2019s climb to Taktsang monastery, clinging to a cliff 900 metres above the valley, then the airport.', ['Tiger\u2019s Nest'], ['Tiger\u2019s Nest (Taktsang) monastery hike'], ['Paro', 'Tiger\u2019s Nest', 12, 'CAR'], [1, 1, 0], -1],
    ]),
  },
];

/**
 * Existing packages the demo reshapes so every package has a complete,
 * sensible itinerary. Values here are additive to the *itinerary only* — the
 * package row's own title/price/margin belong to whoever created it and are
 * never overwritten.
 */
export const EXISTING_PACKAGE_ITINERARIES = [
  {
    id: 'b0000000-0000-0000-0000-000000000001',
    dest: 'sriLanka',
    cover: 'https://images.unsplash.com/photo-1612862862126-865765df2ded?w=1200&auto=format&fit=crop&q=70',
    itinerary: [
      ['Arrival in Colombo', 'Met on arrival and transferred to the city. Evening at Galle Face Green watching the kites and the sunset.', ['Colombo'], ['Airport Meet and Greet', 'Galle Face Green sunset walk'], ['Colombo', 'Colombo', 32, 'VAN'], [0, 0, 1], 0],
      ['Sigiriya Rock Fortress', 'Early start for the Cultural Triangle and the climb to the 5th-century sky palace of Sigiriya, with the water gardens below.', ['Sigiriya', 'Dambulla'], ['Climbing Sigiriya Lion Rock', 'Dambulla Cave Temple visit'], ['Colombo', 'Sigiriya', 175, 'VAN'], [1, 1, 1], 1],
      ['Kandy and the Tea Estates', 'Through the spice gardens to Kandy for the Temple of the Sacred Tooth Relic, then up into the tea hills.', ['Kandy', 'Nuwara Eliya'], ['Temple of the Sacred Tooth Relic visit', 'Guided Tea Plantation and Factory Tour'], ['Sigiriya', 'Kandy', 92, 'VAN'], [1, 1, 1], 2],
      ['Beach Day at Bentota', 'Down to the southern coast for a day on the sand, a Madu River boat safari and a farewell seafood dinner.', ['Bentota'], ['Madu River boat safari'], ['Nuwara Eliya', 'Bentota', 210, 'VAN'], [1, 1, 1], 5],
    ],
  },
  {
    id: 'b0000000-0000-0000-0000-000000000002',
    dest: 'maldives',
    cover: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1200&auto=format&fit=crop&q=70',
    itinerary: [
      ['Arrival in Mal\u00e9', 'Met at Velana International and transferred by speedboat to your island resort for sunset cocktails.', ['Mal\u00e9', 'North Mal\u00e9 Atoll'], ['Airport Meet and Greet'], ['Mal\u00e9', 'North Mal\u00e9 Atoll', 45, 'BOAT'], [0, 0, 1], 0],
      ['Reef Exploration', 'Guided house-reef snorkeling among the corals, an afternoon at leisure and a couples spa ritual.', ['North Mal\u00e9 Atoll'], ['Guided house-reef snorkeling', 'Couples spa ritual'], null, [1, 1, 1], 0],
      ['Sunset Cruise and Departure', 'A final morning swim, then a sunset dolphin cruise and the transfer back to Mal\u00e9 for departure.', ['Mal\u00e9'], ['Sunset dolphin cruise'], ['North Mal\u00e9 Atoll', 'Mal\u00e9', 45, 'BOAT'], [1, 0, 0], -1],
    ],
  },
  {
    id: 'b0000000-0000-0000-0000-000000000003',
    dest: 'thailand',
    cover: 'https://images.unsplash.com/photo-1528181304800-259b08848526?w=1200&auto=format&fit=crop&q=70',
    itinerary: [
      ['Arrival in Bangkok', 'Arrive and transfer to your riverside hotel. Evening at Asiatique with dinner by the water.', ['Bangkok'], ['Airport Meet and Greet'], ['Bangkok', 'Bangkok', 30, 'VAN'], [0, 0, 1], 0],
      ['Bangkok Temples and Canals', 'The Grand Palace and Wat Pho, then a longtail boat through the Thonburi canals.', ['Bangkok'], ['Grand Palace tour'], null, [1, 1, 1], 0],
      ['Fly to Phuket', 'Morning flight south. Afternoon on Patong beach and a Phuket old town walk at sunset.', ['Phuket'], ['Night bazaar walk'], ['Bangkok', 'Phuket', 690, 'FLIGHT'], [1, 0, 1], 3],
      ['Phi Phi Island Safari', 'Speedboat day trip through Maya Bay and Pileh Lagoon with snorkeling and a beach lunch.', ['Phi Phi Islands'], ['Phi Phi island-hopping by speedboat'], ['Phuket', 'Phi Phi Islands', 48, 'BOAT'], [1, 1, 0], 3],
      ['Elephant Sanctuary and Departure', 'Morning at an ethical elephant sanctuary, then the transfer to Phuket airport.', ['Phuket'], ['Ethical elephant sanctuary visit'], ['Phuket', 'Phuket', 30, 'VAN'], [1, 0, 0], -1],
    ],
  },
  {
    id: 'b0000000-0000-0000-0000-000000000004',
    dest: 'uae',
    cover: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1200&auto=format&fit=crop&q=70',
    itinerary: [
      ['Arrival in Dubai', 'Arrive at DXB and check in downtown. Evening at the Dubai Fountain with dinner at Souk Al Bahar.', ['Downtown Dubai'], ['Airport Meet and Greet', 'Dubai Fountain show'], ['Dubai', 'Downtown Dubai', 20, 'VAN'], [0, 0, 1], 3],
      ['Burj Khalifa and the Mall', 'Observation deck at 124 floors, then the Dubai Mall, the aquarium and the fashion avenue.', ['Downtown Dubai'], ['Burj Khalifa observation deck', 'Dubai Mall & aquarium visit'], null, [1, 1, 0], 3],
      ['Desert Safari', 'Dune bashing, camel rides and sandboarding in the red dunes, ending with a barbecue dinner under the stars.', ['Dubai Desert'], ['Desert safari with BBQ dinner', 'Dune bashing', 'Camel ride'], ['Downtown Dubai', 'Dubai Desert', 65, 'CAR'], [1, 0, 1], 3],
      ['Abu Dhabi Day Trip and Departure', 'The Sheikh Zayed Grand Mosque and the Louvre Abu Dhabi before the transfer to the airport.', ['Abu Dhabi'], ['Sheikh Zayed Grand Mosque visit'], ['Dubai', 'Abu Dhabi', 140, 'VAN'], [1, 1, 0], -1],
    ],
  },
  {
    id: 'b0000000-0000-0000-0000-000000000005',
    dest: 'bali',
    cover: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1200&auto=format&fit=crop&q=70',
    itinerary: [
      ['Arrival in Ubud', 'Met at Denpasar and driven up to Ubud. Evening walk through the rice terraces with a welcome dinner.', ['Ubud'], ['Airport Meet and Greet'], ['Ubud', 'Ubud', 42, 'VAN'], [0, 0, 1], 0],
      ['Ubud and the Sacred Spring', 'Tegallalang terraces, the Monkey Forest and a purification ritual at Tirta Empul.', ['Tegallalang', 'Ubud', 'Tirta Empul'], ['Tegallalang rice terrace walk', 'Ubud Monkey Forest visit', 'Tirta Empul purification ritual'], ['Ubud', 'Tegallalang', 14, 'CAR'], [1, 1, 1], 0],
      ['Mount Batur Sunrise', 'Pre-dawn trek up Mount Batur for sunrise above the clouds, with the afternoon free to recover.', ['Kintamani'], ['Mount Batur sunrise trek'], ['Ubud', 'Kintamani', 38, 'CAR'], [1, 0, 1], 0],
      ['To the Coast and Uluwatu', 'Transfer to Seminyak, then Uluwatu Temple for the sunset Kecak fire dance.', ['Seminyak', 'Uluwatu'], ['Uluwatu Temple sunset & Kecak dance'], ['Ubud', 'Seminyak', 34, 'VAN'], [1, 0, 1], 2],
      ['Beach Day and Departure', 'A slow morning on the beach, a couples spa ritual and a final dinner in Jimbaran before departure.', ['Seminyak'], ['Couples spa ritual', 'Jimbaran seafood beach dinner'], ['Seminyak', 'Seminyak', 18, 'VAN'], [1, 0, 1], -1],
    ],
  },
  {
    id: 'b0000000-0000-0000-0000-000000000006',
    dest: 'europe',
    cover: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1200&auto=format&fit=crop&q=70',
    itinerary: [
      ['Arrival in London', 'Arrive at Heathrow and transfer to the Tower Hotel. Evening walk along the South Bank with the city lights on.', ['London'], ['Airport Meet and Greet'], ['London', 'London', 28, 'CAR'], [0, 0, 1], 0],
      ['London Landmarks', 'Westminster, Big Ben and the British Museum, with a ride on the London Eye in the late afternoon.', ['London'], ['Big Ben and Westminster walking tour', 'British Museum guided visit', 'London Eye ride'], null, [1, 1, 1], 0],
      ['Eurostar to Paris', 'The train through the Channel Tunnel to Paris, an afternoon on the Champs-\u00c9lysées and a Seine dinner cruise.', ['Paris'], ['Eurostar rail crossing', 'Seine dinner cruise'], ['London', 'Paris', 460, 'TRAIN'], [1, 0, 1], 1],
      ['Paris and Versailles', 'The Louvre in the morning, then the Palace of Versailles and its gardens in the afternoon.', ['Paris', 'Versailles'], ['Louvre Museum guided visit', 'Palace of Versailles day trip'], ['Paris', 'Versailles', 22, 'CAR'], [1, 1, 1], 1],
      ['Thalys to Amsterdam', 'High-speed rail north to the canals, an afternoon cruise and a visit to the Anne Frank House.', ['Amsterdam'], ['Amsterdam canal cruise', 'Anne Frank House visit'], ['Paris', 'Amsterdam', 520, 'TRAIN'], [1, 0, 1], 2],
      ['Amsterdam to Rome', 'Flight south to Rome. Afternoon in Trastevere and a pasta-making class in the evening.', ['Rome'], ['Italian pasta-making class'], ['Amsterdam', 'Rome', 1300, 'FLIGHT'], [1, 0, 1], 3],
      ['Ancient Rome and Departure', 'The Colosseum, the Roman Forum and the Vatican Museums before the transfer to Fiumicino.', ['Rome', 'Vatican City'], ['Colosseum and Roman Forum tour', 'Vatican Museums and Sistine Chapel'], ['Rome', 'Vatican City', 8, 'CAR'], [1, 1, 0], -1],
    ],
  },
  {
    id: 'b0000000-0000-0000-0000-000000000007',
    dest: 'japan',
    cover: 'https://images.unsplash.com/photo-1526481280693-3bfa7568e0f3?w=1200&auto=format&fit=crop&q=70',
    itinerary: [
      ['Arrival in Tokyo', 'Arrive at Narita and transfer into the city. Evening walk through Shinjuku with an izakaya dinner.', ['Tokyo'], ['Airport Meet and Greet', 'Shibuya Crossing walk'], ['Tokyo', 'Tokyo', 70, 'VAN'], [0, 0, 1], 0],
      ['Tokyo in Depth', 'Meiji Shrine, the Tsukiji outer market and Asakusa\u2019s Nakamise street, ending at Akihabara.', ['Tokyo', 'Asakusa'], ['Meiji Shrine visit', 'Tsukiji Outer Market breakfast tour'], null, [1, 1, 0], 0],
      ['Mt Fuji and Hakone', 'Lake Ashi, the Hakone Ropeway and an overnight ryokan with a hot-spring bath and kaiseki dinner.', ['Mt Fuji', 'Hakone'], ['Mt Fuji and Lake Ashi day trip', 'Onsen ryokan experience'], ['Tokyo', 'Hakone', 95, 'TRAIN'], [1, 0, 1], 2],
      ['Kyoto by Bullet Train', 'Shinkansen to Kyoto. Afternoon at Fushimi Inari and the Gion geisha district in the evening.', ['Kyoto', 'Fushimi'], ['JR Pass activation and rail travel', 'Fushimi Inari shrine walk', 'Gion geisha district evening walk'], ['Hakone', 'Kyoto', 400, 'TRAIN'], [1, 1, 1], 1],
      ['Kyoto Temples and Tea', 'The Golden Pavilion and the Arashiyama bamboo grove, then a formal tea ceremony.', ['Kyoto', 'Arashiyama'], ['Kinkaku-ji Golden Pavilion', 'Arashiyama Bamboo Grove visit', 'Traditional tea ceremony'], ['Kyoto', 'Kyoto', 24, 'CAR'], [1, 1, 1], 1],
      ['Nara Deer Park', 'A day trip to Nara for the deer park and Todaiji\u2019s great bronze Buddha.', ['Nara'], ['Nara deer park day trip'], ['Kyoto', 'Nara', 45, 'TRAIN'], [1, 1, 0], 1],
      ['Osaka and Departure', 'Train to Osaka for the castle and a Dotonbori food crawl before the transfer to the airport.', ['Osaka'], ['Osaka Castle visit', 'Dotonbori food crawl'], ['Kyoto', 'Osaka', 45, 'TRAIN'], [1, 1, 0], -1],
    ],
  },
];
