/**
 * Destinations for travel packages
 * Organized by popular and other international destinations
 */
// Per-company reference data. Replace with this company's actual destinations/locations/activities before shipping a new deployment.

// Popular International Destinations
export const POPULAR_INTERNATIONAL = [
  { value: 'Almaty', label: 'Almaty, Kazakhstan' },
  { value: 'Bali', label: 'Bali, Indonesia' },
  { value: 'Bangkok & Pattaya', label: 'Bangkok & Pattaya, Thailand' },
  { value: 'Dubai', label: 'Dubai, UAE' },
  { value: 'Malaysia', label: 'Malaysia' },
  { value: 'Maldives', label: 'Maldives' },
  { value: 'Mauritius', label: 'Mauritius' },
  { value: 'Phuket & Krabi', label: 'Phuket & Krabi, Thailand' },
  { value: 'Seychelles', label: 'Seychelles' },
  { value: 'Singapore', label: 'Singapore' },
  { value: 'Sri Lanka', label: 'Sri Lanka' },
  { value: 'Thailand', label: 'Thailand' },
  { value: 'Vietnam', label: 'Vietnam' },
];

// Additional International Destinations
export const OTHER_INTERNATIONAL = [
  { value: 'Abu Dhabi', label: 'Abu Dhabi, UAE' },
  { value: 'Amsterdam', label: 'Amsterdam, Netherlands' },
  { value: 'Athens', label: 'Athens, Greece' },
  { value: 'Australia', label: 'Australia' },
  { value: 'Austria', label: 'Austria' },
  { value: 'Azerbaijan', label: 'Azerbaijan (Baku)' },
  { value: 'Barcelona', label: 'Barcelona, Spain' },
  { value: 'Bhutan', label: 'Bhutan' },
  { value: 'Cambodia', label: 'Cambodia' },
  { value: 'Canada', label: 'Canada' },
  { value: 'China', label: 'China' },
  { value: 'Croatia', label: 'Croatia' },
  { value: 'Czech Republic', label: 'Czech Republic' },
  { value: 'Egypt', label: 'Egypt' },
  { value: 'France', label: 'France' },
  { value: 'Georgia', label: 'Georgia' },
  { value: 'Germany', label: 'Germany' },
  { value: 'Greece', label: 'Greece' },
  { value: 'Hong Kong', label: 'Hong Kong' },
  { value: 'Iceland', label: 'Iceland' },
  { value: 'Italy', label: 'Italy' },
  { value: 'Japan', label: 'Japan' },
  { value: 'Jordan', label: 'Jordan' },
  { value: 'Kenya', label: 'Kenya' },
  { value: 'London', label: 'London, UK' },
  { value: 'Macau', label: 'Macau' },
  { value: 'Morocco', label: 'Morocco' },
  { value: 'Nepal', label: 'Nepal' },
  { value: 'New Zealand', label: 'New Zealand' },
  { value: 'Norway', label: 'Norway' },
  { value: 'Paris', label: 'Paris, France' },
  { value: 'Portugal', label: 'Portugal' },
  { value: 'Santorini', label: 'Santorini, Greece' },
  { value: 'Saudi Arabia', label: 'Saudi Arabia' },
  { value: 'Scotland', label: 'Scotland' },
  { value: 'South Africa', label: 'South Africa' },
  { value: 'South Korea', label: 'South Korea' },
  { value: 'Spain', label: 'Spain' },
  { value: 'Switzerland', label: 'Switzerland' },
  { value: 'Taiwan', label: 'Taiwan' },
  { value: 'Tanzania', label: 'Tanzania' },
  { value: 'Turkey', label: 'Turkey' },
  { value: 'UK', label: 'United Kingdom' },
  { value: 'USA', label: 'United States' },
];

// Combined list for search functionality
export const ALL_DESTINATIONS = [
  ...POPULAR_INTERNATIONAL,
  ...OTHER_INTERNATIONAL,
].sort((a, b) => a.label.localeCompare(b.label));

// Lowercase country/location -> broad region, used by
// services/api/packages.transform.ts to bucket packages by region. Distinct
// from the picker lists above (those are UI option lists; this is a
// normalization lookup) — co-located here since both are per-client
// reference data to replace before shipping a new deployment.
export const COUNTRY_REGION_MAP: Record<string, string> = {
  indonesia: 'Asia',
  maldives: 'Asia',
  thailand: 'Asia',
  uae: 'Middle East',
  'united arab emirates': 'Middle East',
  dubai: 'Middle East',
  'abu dhabi': 'Middle East',
  malaysia: 'Asia',
  singapore: 'Asia',
  kazakhstan: 'Asia',
  mauritius: 'Africa',
  seychelles: 'Africa',
  vietnam: 'Asia',
  'sri lanka': 'Asia',
  nepal: 'Asia',
  bhutan: 'Asia',
  japan: 'Asia',
  'south korea': 'Asia',
  china: 'Asia',
  'hong kong': 'Asia',
  'indian ocean': 'Asia',
  bali: 'Asia',
  switzerland: 'Europe',
  france: 'Europe',
  italy: 'Europe',
  spain: 'Europe',
  greece: 'Europe',
  turkey: 'Europe',
  austria: 'Europe',
  germany: 'Europe',
  netherlands: 'Europe',
  'united kingdom': 'Europe',
  england: 'Europe',
  scotland: 'Europe',
  ireland: 'Europe',
  portugal: 'Europe',
  croatia: 'Europe',
  sweden: 'Europe',
  norway: 'Europe',
  finland: 'Europe',
  denmark: 'Europe',
  'czech republic': 'Europe',
  hungary: 'Europe',
  egypt: 'Africa',
  kenya: 'Africa',
  'south africa': 'Africa',
  tanzania: 'Africa',
  morocco: 'Africa',
  canada: 'Americas',
  'united states': 'Americas',
  usa: 'Americas',
  mexico: 'Americas',
  brazil: 'Americas',
  argentina: 'Americas',
  peru: 'Americas',
  chile: 'Americas',
  australia: 'Oceania',
  'new zealand': 'Oceania',
  fiji: 'Oceania',
  oman: 'Middle East',
  qatar: 'Middle East',
  'saudi arabia': 'Middle East',
  jordan: 'Middle East',
};
