import { z } from 'zod';
import { createPageAdapter } from '../collectionEngine.js';

const TABS = ['leads', 'billing', 'users', 'itineraries', 'website', 'my-performance'];
const tabScope = z.object({ tab: z.enum(TABS) }).strict();

const source = (name, path, fields, transform, tab, role) => ({
  name,
  shape: 'singleton',
  envKey: 'ANALYTICS_SERVICE_URL',
  path,
  listPath: 'data',
  recordKind: 'analytics',
  fields: ['id', ...fields],
  transform,
  label: `${name} analytics`,
  when: (ctx, scope) => scope.tab === tab && (!role || ctx.user.role === role),
});

export const analyticsAdapter = createPageAdapter({
  key: 'analytics',
  scopeSchema: tabScope,
  scopeLabel: (scope) => `Analytics · ${scope.tab}`,
  sources: [
    source(
      'leads',
      '/api/v1/analytics/leads/overview',
      ['totalLeads', 'new', 'contacted', 'interested', 'quoted', 'converted'],
      (data) => ({ id: 'leads', ...data.stats }),
      'leads',
    ),
    source(
      'billing',
      '/api/v1/analytics/billing/overview',
      ['totalRevenue', 'totalOutstanding', 'totalPotentialRevenue', 'pendingInvoices'],
      (data) => ({ id: 'billing', ...data.stats }),
      'billing',
    ),
    source(
      'users',
      '/api/v1/analytics/users/overview',
      ['totalUsers', 'activeUsers', 'inactiveUsers', 'verifiedUsers', 'usersWithBookings', 'conversionRate'],
      (data) => ({ id: 'users', ...data.stats }),
      'users',
      'admin',
    ),
    source(
      'itineraries',
      '/api/v1/analytics/packages/overview',
      ['totalItineraries', 'totalInquiries', 'totalConversions'],
      (data) => ({ id: 'itineraries', ...data.stats }),
      'itineraries',
      'admin',
    ),
    source(
      'website',
      '/api/v1/analytics/website/overview',
      ['totalSearches', 'totalBookings', 'uniqueDestinations', 'uniqueActivities', 'conversionRate'],
      (data) => ({ id: 'website', ...data.stats }),
      'website',
      'admin',
    ),
    source(
      'my-performance',
      '/api/v1/analytics/salesreps/me/performance',
      ['leadsAssigned', 'converted', 'pending', 'conversionRate'],
      (data) => ({ id: 'my-performance', ...data.performance }),
      'my-performance',
      'salesRep',
    ),
  ],
  rules: [
    {
      source: 'leads',
      rule: 'ratioBelow',
      numeratorField: 'converted',
      denominatorField: 'totalLeads',
      threshold: 0.2,
      section: 'attention',
      severity: 'warning',
      text: 'Lead conversion is below one in five for this period.',
    },
    {
      source: 'billing',
      rule: 'thresholdExceeded',
      field: 'pendingInvoices',
      threshold: 0,
      section: 'attention',
      severity: 'warning',
      text: 'Pending invoices need review.',
    },
    {
      source: 'billing',
      rule: 'thresholdExceeded',
      field: 'totalOutstanding',
      threshold: 10_000,
      factKind: 'amount',
      section: 'attention',
      severity: 'warning',
      text: 'Outstanding billing value is high.',
    },
    {
      source: 'users',
      rule: 'ratioBelow',
      numeratorField: 'activeUsers',
      denominatorField: 'totalUsers',
      threshold: 0.8,
      section: 'attention',
      severity: 'warning',
      text: 'More than one in five user accounts is inactive.',
    },
    {
      source: 'itineraries',
      rule: 'ratioBelow',
      numeratorField: 'totalConversions',
      denominatorField: 'totalInquiries',
      threshold: 0.2,
      section: 'attention',
      severity: 'warning',
      text: 'Package inquiry conversion is below one in five.',
    },
    {
      source: 'website',
      rule: 'ratioBelow',
      numeratorField: 'totalBookings',
      denominatorField: 'totalSearches',
      threshold: 0.1,
      section: 'attention',
      severity: 'warning',
      text: 'Fewer than one in ten website searches becomes a booking.',
    },
    {
      source: 'my-performance',
      rule: 'ratioBelow',
      numeratorField: 'converted',
      denominatorField: 'leadsAssigned',
      threshold: 0.2,
      section: 'attention',
      severity: 'warning',
      text: 'Your conversion is below one in five for this period.',
    },
    {
      source: 'my-performance',
      rule: 'thresholdExceeded',
      field: 'pending',
      threshold: 0,
      section: 'experienced_view',
      severity: 'info',
      text: 'You have pending leads to inspect.',
    },
  ],
  questionTemplates: [
    (bundle) => `What stands out in ${bundle.scope?.tab ?? 'this'} analytics?`,
    'Which metric should I investigate first?',
    'What is underperforming in this period?',
  ],
});
