import { z } from 'zod';
import { createPageAdapter } from '../collectionEngine.js';

export const overviewAdapter = createPageAdapter({
  key: 'overview',
  scopeSchema: z.object({}).strict(),
  scopeLabel: () => 'Overview',
  sources: [
    {
      name: 'dashboard',
      shape: 'singleton',
      envKey: 'ANALYTICS_SERVICE_URL',
      path: '/api/v1/dashboard/stats',
      listPath: 'data',
      recordKind: 'dashboard',
      fields: [
        'id',
        'leadsTotal',
        'leadsNew',
        'leadsConverted',
        'bookingsTotal',
        'bookingsConfirmed',
        'bookingsPending',
        'revenueTotal',
        'revenueCollected',
        'packagesTotal',
        'packagesPublished',
      ],
      transform: (data) => ({
        id: 'overview',
        leadsTotal: data.leads?.total ?? 0,
        leadsNew: data.leads?.new ?? 0,
        leadsConverted: data.leads?.converted ?? 0,
        bookingsTotal: data.bookings?.total ?? 0,
        bookingsConfirmed: data.bookings?.confirmed ?? 0,
        bookingsPending: data.bookings?.pending ?? 0,
        revenueTotal: data.revenue?.total ?? 0,
        revenueCollected: data.revenue?.collected ?? 0,
        packagesTotal: data.packages?.total ?? 0,
        packagesPublished: data.packages?.published ?? 0,
      }),
      label: 'Dashboard totals',
    },
  ],
  rules: [
    {
      source: 'dashboard',
      rule: 'ratioBelow',
      numeratorField: 'leadsConverted',
      denominatorField: 'leadsTotal',
      threshold: 0.2,
      section: 'attention',
      severity: 'warning',
      text: 'Fewer than one in five leads in this view are confirmed.',
    },
    {
      source: 'dashboard',
      rule: 'thresholdExceeded',
      field: 'bookingsPending',
      threshold: 0,
      section: 'attention',
      severity: 'warning',
      text: 'Pending bookings need review.',
    },
    {
      source: 'dashboard',
      rule: 'ratioBelow',
      numeratorField: 'revenueCollected',
      denominatorField: 'revenueTotal',
      threshold: 0.5,
      section: 'attention',
      severity: 'warning',
      text: 'Less than half of billed revenue has been collected.',
    },
    {
      source: 'dashboard',
      rule: 'ratioBelow',
      numeratorField: 'packagesPublished',
      denominatorField: 'packagesTotal',
      threshold: 0.5,
      section: 'experienced_view',
      severity: 'info',
      text: 'Less than half of the package catalogue is published.',
    },
  ],
  questionTemplates: [
    'What needs attention across the business?',
    'Where is conversion weak?',
    'What should I inspect first today?',
  ],
});
