/**
 * Sample invoice data for development and testing
 */
export const sampleInvoices = [
  {
    id: "INV-001",
    customerName: "John Smith",
    email: "john@example.com",
    packageName: "Paris Romance Getaway",
    amount: 2499,
    tax: 250,
    total: 2749,
    status: "paid",
    dueDate: "2025-10-20",
    issuedDate: "2025-10-01",
    paymentDate: "2025-10-15",
    paymentMethod: "Credit Card",
    items: [
      { description: "Flight Tickets", quantity: 2, rate: 800, amount: 1600 },
      {
        description: "Hotel Accommodation (4 nights)",
        quantity: 1,
        rate: 600,
        amount: 600,
      },
      {
        description: "Tour Guide & Activities",
        quantity: 1,
        rate: 299,
        amount: 299,
      },
    ],
    notes: "Payment received. Thank you!",
  },
  {
    id: "INV-002",
    customerName: "Emma Wilson",
    email: "emma@example.com",
    packageName: "Bali Family Adventure",
    amount: 1899,
    tax: 190,
    total: 2089,
    status: "pending",
    dueDate: "2025-10-25",
    issuedDate: "2025-10-05",
    paymentDate: null,
    paymentMethod: null,
    items: [
      { description: "Flight Tickets", quantity: 4, rate: 400, amount: 1600 },
      {
        description: "Resort Accommodation (6 nights)",
        quantity: 1,
        rate: 299,
        amount: 299,
      },
    ],
    notes: "Awaiting customer payment",
  },
  {
    id: "INV-003",
    customerName: "Robert Brown",
    email: "robert@example.com",
    packageName: "Dubai Luxury Escape",
    amount: 3299,
    tax: 330,
    total: 3629,
    status: "partial",
    dueDate: "2025-10-30",
    issuedDate: "2025-10-08",
    paymentDate: "2025-10-18",
    paymentMethod: "Bank Transfer",
    paidAmount: 1815,
    items: [
      { description: "Flight Tickets", quantity: 3, rate: 1000, amount: 3000 },
      {
        description: "Luxury Hotel (3 nights)",
        quantity: 1,
        rate: 299,
        amount: 299,
      },
    ],
    notes: "Advance payment received. Balance due before travel date.",
  },
];
