export const LIFECYCLE_STATUSES = [
  'NEW', 'DRAFTING', 'QUOTED', 'REVISION', 'APPROVED',
  'BOOKING_IN_PROGRESS', 'CONFIRMED', 'CLOSED_LOST',
  'BOOKING_FAILED', 'CANCELLED',
];

// Populated in Phase 2
export const ALLOWED_TRANSITIONS = {};

export const TERMINAL_STATUSES = ['CLOSED_LOST', 'CANCELLED'];

export const REQUIRES_LOST_REASON = ['CLOSED_LOST'];
