export const LIFECYCLE_STATUSES = [
  'PENDING_VERIFICATION',
  'NEW', 'DRAFTING', 'QUOTED', 'REVISION', 'APPROVED',
  'BOOKING_IN_PROGRESS', 'CONFIRMED', 'CLOSED_LOST',
  'BOOKING_FAILED', 'CANCELLED',
];

export const ALLOWED_TRANSITIONS = {
  PENDING_VERIFICATION: ['NEW', 'CLOSED_LOST'],
  NEW:                ['DRAFTING', 'CLOSED_LOST'],
  DRAFTING:           ['QUOTED', 'CLOSED_LOST'],
  QUOTED:             ['REVISION', 'APPROVED', 'CLOSED_LOST'],
  REVISION:           ['DRAFTING', 'QUOTED', 'APPROVED', 'CLOSED_LOST'],
  APPROVED:           ['BOOKING_IN_PROGRESS', 'CLOSED_LOST'],
  BOOKING_IN_PROGRESS: ['CONFIRMED', 'BOOKING_FAILED'],
  BOOKING_FAILED:     ['BOOKING_IN_PROGRESS', 'REVISION', 'CLOSED_LOST'],
  CONFIRMED:          ['CANCELLED'],
  CLOSED_LOST:        [],
  CANCELLED:          [],
};

export const TERMINAL_STATUSES = ['CLOSED_LOST', 'CANCELLED'];

export const REQUIRES_LOST_REASON = ['CLOSED_LOST'];
