/**
 * Popular locations/attractions by destination
 * For quick selection when creating day itineraries
 */

// International Destinations
export const LOCATIONS_BY_DESTINATION = {
  // Popular International
  'Almaty, Kazakhstan': [
    'Medeu Ice Skating Rink',
    'Shymbulak Ski Resort',
    'Kok Tobe Hill',
    'Zenkov Cathedral',
    'Central State Museum',
    'Big Almaty Lake',
    'Green Bazaar',
    'First President Park',
    'Almaty Central Mosque',
    'Panfilov Park',
    'Ascension Cathedral',
    'Almaty Zoo',
    'Charyn Canyon',
    'Kolsai Lakes',
    'Almaty Opera House',
  ],
  'Bali, Indonesia': [
    'Uluwatu Temple',
    'Tanah Lot Temple',
    'Tegalalang Rice Terraces',
    'Sacred Monkey Forest',
    'Mount Batur',
    'Ubud Palace',
    'Seminyak Beach',
    'Kuta Beach',
    'Nusa Dua Beach',
    'Waterbom Bali',
    'Besakih Temple',
    'Tirta Empul Temple',
    'Tegenungan Waterfall',
    'Sekumpul Waterfall',
    'Nusa Penida',
    'Lempuyang Temple',
    'Campuhan Ridge Walk',
    'Bali Safari & Marine Park',
    'Gitgit Waterfall',
    'Jatiluwih Rice Terraces',
  ],
  'Bangkok & Pattaya, Thailand': [
    'Grand Palace Bangkok',
    'Wat Arun',
    'Wat Pho',
    'Floating Market',
    'Chatuchak Market',
    'Khao San Road',
    'Pattaya Beach',
    'Walking Street Pattaya',
    'Coral Island',
    'Nong Nooch Garden',
    'Sanctuary of Truth',
    'Wat Saket (Golden Mount)',
    'Jim Thompson House',
    'Lumpini Park',
    'MBK Center',
    'Siam Paragon',
    'Wat Benchamabophit',
    'Jomtien Beach',
    'Koh Larn',
    'Ripley\'s Believe It or Not',
    'Art in Paradise',
    'Pattaya Floating Market',
    'Mini Siam',
  ],
  'Dubai, UAE': [
    'Burj Khalifa',
    'Dubai Mall',
    'Dubai Fountain',
    'Palm Jumeirah',
    'Burj Al Arab',
    'Dubai Marina',
    'Gold Souk',
    'Spice Souk',
    'Dubai Creek',
    'Atlantis Aquaventure',
    'Desert Safari',
    'Dubai Frame',
    'Global Village',
    'Mall of Emirates',
    'Ski Dubai',
    'Dubai Aquarium',
    'Dubai Miracle Garden',
    'IMG Worlds of Adventure',
    'Dubai Parks and Resorts',
    'Jumeirah Beach',
    'Dubai Museum',
    'Al Fahidi Historical Neighbourhood',
    'Dubai Opera',
    'La Perle Show',
    'Dubai Marina Walk',
    'The View at The Palm',
  ],
  'Malaysia': [
    'Petronas Towers',
    'Batu Caves',
    'Genting Highlands',
    'Langkawi Island',
    'Penang',
    'Cameron Highlands',
    'Malacca',
    'KL Tower',
    'Aquaria KLCC',
    'Sunway Lagoon',
    'Legoland Malaysia',
    'Langkawi Sky Bridge',
    'Penang Hill',
    'Kek Lok Si Temple',
    'Strait of Malacca',
    'Red Square Malacca',
    'Taman Negara',
    'Perhentian Islands',
    'Tioman Island',
    'Mount Kinabalu',
    'Sipadan Island',
  ],
  'Maldives': [
    'Male City',
    'Artificial Beach',
    'Grand Friday Mosque',
    'Coral Reefs',
    'Water Sports Center',
    'Local Island Tour',
    'Sandbank Visit',
    'National Museum',
    'Sultan Park',
    'Fish Market',
    'Mulee-aage Palace',
    'Hukuru Miskiy',
    'Snorkeling',
    'Diving',
    'Sunset Cruise',
    'Dolphin Watching',
    'Island Hopping',
    'Underwater Restaurant',
  ],
  'Mauritius': [
    'Port Louis',
    'Chamarel Seven Colored Earth',
    'Black River Gorges',
    'Le Morne Beach',
    'Ile aux Cerfs',
    'Grand Baie',
    'Pamplemousses Garden',
    'Casela Nature Park',
    'Chamarel Waterfall',
    'Trou aux Cerfs',
    'Blue Bay Marine Park',
    'Flic en Flac Beach',
    'La Vanille Nature Park',
    'SSR Botanical Garden',
    'Aapravasi Ghat',
    'Notre Dame Auxiliatrice',
    'Trou d\'Eau Douce',
    'Ganga Talao',
  ],
  'Phuket & Krabi, Thailand': [
    'Phi Phi Islands',
    'James Bond Island',
    'Phang Nga Bay',
    'Patong Beach',
    'Big Buddha',
    'Old Phuket Town',
    'Railay Beach',
    'Tiger Cave Temple',
    'Emerald Pool',
    'Ao Nang Beach',
    'Kata Beach',
    'Karon Beach',
    'Bangla Road',
    'Wat Chalong',
    'Simon Cabaret Show',
    'Phuket Fantasea',
    'Koh Hong',
    'Koh Poda',
    'Diamond Cave',
    'Hot Springs',
    'Krabi Town',
    'Thung Teao Forest',
  ],
  'Seychelles': [
    'Anse Source d\'Argent',
    'Vallee de Mai',
    'Beau Vallon Beach',
    'Victoria Market',
    'Morne Seychellois',
    'Anse Lazio',
    'Cousin Island',
    'Anse Georgette',
    'Curieuse Island',
    'Aldabra Atoll',
    'Praslin Island',
    'La Digue Island',
    'Sainte Anne Marine Park',
    'Aride Island',
    'Takamaka Bay',
    'Jardin du Roi',
  ],
  'Singapore': [
    'Marina Bay Sands',
    'Gardens by the Bay',
    'Sentosa Island',
    'Universal Studios',
    'Merlion Park',
    'Orchard Road',
    'Chinatown',
    'Little India',
    'Clarke Quay',
    'Singapore Zoo',
    'Night Safari',
    'Jewel Changi',
    'Singapore Flyer',
    'River Safari',
    'Botanic Gardens',
    'Marina Bay',
    'Helix Bridge',
    'ArtScience Museum',
    'S.E.A. Aquarium',
    'Tiger Sky Tower',
    'Fort Siloso',
    'Haw Par Villa',
    'East Coast Park',
  ],
  'Sri Lanka': [
    'Sigiriya Rock',
    'Temple of Tooth',
    'Galle Fort',
    'Yala National Park',
    'Ella',
    'Nuwara Eliya',
    'Tea Plantations',
    'Mirissa Beach',
    'Colombo City',
    'Dambulla Cave Temple',
    'Nine Arch Bridge',
    'Adam\'s Peak',
    'Polonnaruwa',
    'Anuradhapura',
    'Kandy',
    'Bentota',
    'Unawatuna Beach',
    'Hikkaduwa',
    'Sinharaja Forest',
    'Udawalawe National Park',
    'Pinnawala Elephant Orphanage',
    'Ramboda Falls',
  ],
  'Thailand': [
    'Grand Palace',
    'Wat Arun',
    'Floating Market',
    'Chiang Mai',
    'Phuket',
    'Ayutthaya',
    'Sukhothai',
    'Khao Sok National Park',
    'Doi Suthep',
    'Elephant Nature Park',
    'Railay Beach',
    'Koh Samui',
    'Koh Phi Phi',
    'Pai',
    'Mae Hong Son',
    'Erawan Falls',
    'Wat Phra Kaew',
    'Chatuchak Weekend Market',
  ],
  'Vietnam': [
    'Halong Bay',
    'Hanoi Old Quarter',
    'Ho Chi Minh City',
    'Cu Chi Tunnels',
    'Hoi An Ancient Town',
    'Hue Imperial City',
    'Mekong Delta',
    'Sapa',
    'Phong Nha Cave',
    'War Remnants Museum',
    'Notre-Dame Cathedral',
    'Ben Thanh Market',
    'My Son Sanctuary',
    'Ba Na Hills',
    'Golden Bridge',
    'Mui Ne Sand Dunes',
    'Nha Trang',
    'Da Lat',
    'Ban Gioc Falls',
    'Cat Ba Island',
  ],
  'Hongkong & Macau': [
    'Victoria Peak',
    'Hong Kong Disneyland',
    'Ocean Park',
    'Tsim Sha Tsui Promenade',
    'Star Ferry',
    'Temple Street Night Market',
    'Big Buddha (Tian Tan)',
    'Macau Tower',
    'Ruins of St. Paul\'s',
    'Senado Square',
    'Venetian Macau',
    'A-Ma Temple',
    'Coloane Village',
    'Ngong Ping 360',
    'Hong Kong Museum',
    'Lantau Island',
    'Wong Tai Sin Temple',
    'Symphony of Lights',
    'Stanley Market',
    'Repulse Bay',
    'Macau Fisherman\'s Wharf',
    'Guia Fortress',
    'Taipa Village',
    'House of Dancing Water',
  ],
  'Japan': [
    'Tokyo Tower',
    'Mount Fuji',
    'Senso-ji Temple',
    'Osaka Castle',
    'Fushimi Inari Shrine',
    'Hiroshima Peace Memorial',
    'Nara Park',
    'Universal Studios Japan',
    'Tokyo Disneyland',
    'Kyoto Imperial Palace',
    'Arashiyama Bamboo Grove',
    'Golden Pavilion (Kinkaku-ji)',
    'Shinjuku Gyoen',
    'Akihabara',
    'Tokyo Skytree',
    'Shibuya Crossing',
    'Meiji Shrine',
    'Tokyo National Museum',
    'Hakone',
    'Nikko',
    'Takayama',
    'Kanazawa',
    'Miyajima Island',
    'Osaka Aquarium',
    'Dotonbori',
  ],
  'Turkey': [
    'Hagia Sophia',
    'Blue Mosque',
    'Topkapi Palace',
    'Cappadocia',
    'Pamukkale',
    'Ephesus',
    'Grand Bazaar',
    'Bosphorus Cruise',
    'Galata Tower',
    'Basilica Cistern',
    'Troy',
    'Antalya Old Town',
    'Goreme Open Air Museum',
    'Sultanahmet Square',
    'Dolmabahce Palace',
    'Istanbul Archaeology Museum',
    'Spice Bazaar',
    'Hot Air Balloon Ride',
    'Derinkuyu Underground City',
    'Ihlara Valley',
    'Aspendos Theatre',
    'Perge',
    'Side',
    'Bodrum',
    'Kusadasi',
  ],
  'Baku, Azerbaijan': [
    'Flame Towers',
    'Old City (Icherisheher)',
    'Heydar Aliyev Center',
    'Baku Boulevard',
    'Maiden Tower',
    'Palace of the Shirvanshahs',
    'Ateshgah Fire Temple',
    'Gobustan Rock Art',
    'Mud Volcanoes',
    'Carpet Museum',
    'Nizami Street',
    'Yanar Dag',
    'Bibi-Heybat Mosque',
    'Azerbaijan National Museum',
    'Fountain Square',
    'Shirvan National Park',
    'Absheron Peninsula',
    'Little Venice',
    'Baku Crystal Hall',
    'Martyrs\' Lane',
  ],
  'Georgia': [
    'Tbilisi Old Town',
    'Narikala Fortress',
    'Svetitskhoveli Cathedral',
    'Uplistsikhe Cave Town',
    'Gergeti Trinity Church',
    'Ananuri Fortress',
    'Sighnaghi',
    'Kazbegi',
    'Batumi Boulevard',
    'Vardzia Cave Monastery',
    'Prometheus Cave',
    'Peace Bridge',
    'Bridge of Peace',
    'Mtatsminda Park',
    'Jvari Monastery',
    'Gudauri',
    'Bakuriani',
    'Borjomi',
    'Mtskheta',
    'David Gareja',
    'Shatili',
    'Omalo',
  ],
  'Philippines': [
    'Boracay Island',
    'Palawan',
    'El Nido',
    'Chocolate Hills',
    'Banaue Rice Terraces',
    'Intramuros',
    'Rizal Park',
    'Taal Volcano',
    'Mayon Volcano',
    'Coron Island',
    'Puerto Princesa Underground River',
    'Manila Bay',
    'Bohol',
    'Tubbataha Reef',
    'Siargao',
    'Cebu',
    'Donsol',
    'Vigan',
    'Sagada',
    'Banaue',
    'Kawasan Falls',
    'Pagsanjan Falls',
    'Manila Ocean Park',
    'Fort Santiago',
  ],

  // Popular Domestic (India)
  'Andaman & Nicobar Islands': [
    'Port Blair',
    'Cellular Jail',
    'Radhanagar Beach',
    'Havelock Island',
    'Neil Island',
    'Ross Island',
    'Baratang Island',
    'Coral Reefs',
    'Limestone Caves',
    'Elephant Beach',
    'Vijaynagar Beach',
    'Chidiya Tapu',
    'Mount Harriet',
    'Anthropological Museum',
    'Samudrika Naval Museum',
    'Corbyn\'s Cove',
    'North Bay Island',
    'Jolly Buoy Island',
  ],
  'Goa': [
    'Baga Beach',
    'Calangute Beach',
    'Anjuna Beach',
    'Fort Aguada',
    'Basilica of Bom Jesus',
    'Dudhsagar Falls',
    'Chapora Fort',
    'Palolem Beach',
    'Saturday Night Market',
    'Spice Plantation',
    'Arambol Beach',
    'Vagator Beach',
    'Se Cathedral',
    'Old Goa',
    'Dona Paula',
    'Butterfly Beach',
    'Colva Beach',
    'Mangeshi Temple',
    'Shanta Durga Temple',
    'Fontainhas',
  ],
  'Himachal Pradesh': [
    'Shimla',
    'Manali',
    'Kullu',
    'Dharamshala',
    'McLeod Ganj',
    'Dalhousie',
    'Kasol',
    'Rohtang Pass',
    'Solang Valley',
    'Hidimba Temple',
    'Mall Road',
    'Kufri',
    'Jakhoo Temple',
    'Christ Church',
    'The Ridge',
    'Hadimba Devi Temple',
    'Manu Temple',
    'Great Himalayan National Park',
    'Spiti Valley',
    'Kinnaur',
    'Bir Billing',
    'Triund',
  ],
  'Kashmir': [
    'Dal Lake',
    'Srinagar',
    'Gulmarg',
    'Pahalgam',
    'Sonamarg',
    'Nishat Bagh',
    'Shalimar Bagh',
    'Shankaracharya Temple',
    'Betaab Valley',
    'Aru Valley',
    'Hazratbal Shrine',
    'Jamia Masjid',
    'Mughal Gardens',
    'Chashme Shahi',
    'Pari Mahal',
    'Gondola Ride',
    'Thajiwas Glacier',
    'Apharwat Peak',
    'Tulip Garden',
    'Wular Lake',
  ],
  'Kerala': [
    'Munnar',
    'Alleppey Backwaters',
    'Kovalam Beach',
    'Thekkady',
    'Wayanad',
    'Kochi',
    'Fort Kochi',
    'Athirapally Falls',
    'Varkala Beach',
    'Tea Gardens',
    'Houseboat',
    'Periyar National Park',
    'Mattupetty Dam',
    'Eravikulam National Park',
    'Chinese Fishing Nets',
    'Jewish Synagogue',
    'Bekal Fort',
    'Kumarakom',
    'Marari Beach',
    'Silent Valley',
    'Guruvayur Temple',
  ],
  'Rajasthan': [
    'Jaipur',
    'Amber Fort',
    'Hawa Mahal',
    'City Palace Jaipur',
    'Udaipur',
    'Lake Pichola',
    'City Palace Udaipur',
    'Jaisalmer Fort',
    'Sand Dunes',
    'Jodhpur',
    'Mehrangarh Fort',
    'Pushkar',
    'Ranthambore National Park',
    'Jantar Mantar',
    'Nahargarh Fort',
    'Jal Mahal',
    'Chittorgarh Fort',
    'Kumbhalgarh Fort',
    'Ranakpur Jain Temple',
    'Bundi',
    'Mount Abu',
    'Keoladeo National Park',
    'Desert National Park',
  ],
  'Northeast India': [
    'Kaziranga National Park',
    'Shillong',
    'Cherrapunji',
    'Tawang Monastery',
    'Gangtok',
    'Tsomgo Lake',
    'Nathula Pass',
    'Mawlynnong Village',
    'Living Root Bridges',
    'Majuli Island',
    'Umiam Lake',
    'Elephant Falls',
    'Seven Sisters Falls',
    'Dawki',
    'Lachung',
    'Lachen',
    'Gurudongmar Lake',
    'Yumthang Valley',
    'Ziro Valley',
    'Manas National Park',
  ],

  // Common domestic locations
  'Delhi': [
    'Red Fort',
    'Qutub Minar',
    'India Gate',
    'Lotus Temple',
    'Humayun\'s Tomb',
    'Akshardham Temple',
    'Chandni Chowk',
    'Connaught Place',
    'Jama Masjid',
    'Raj Ghat',
    'Gandhi Smriti',
    'Lodi Gardens',
    'Safdarjung Tomb',
    'Purana Qila',
    'National Museum',
    'National Gallery of Modern Art',
    'Dilli Haat',
    'Khan Market',
  ],
  'Agra': [
    'Taj Mahal',
    'Agra Fort',
    'Fatehpur Sikri',
    'Mehtab Bagh',
    'Itmad-ud-Daulah',
    'Jama Masjid',
    'Akbar\'s Tomb',
    'Mariam\'s Tomb',
    'Chini Ka Rauza',
    'Gurudwara Guru Ka Taal',
  ],
  'Jaipur': [
    'Amber Fort',
    'Hawa Mahal',
    'City Palace',
    'Jantar Mantar',
    'Jal Mahal',
    'Nahargarh Fort',
    'Birla Temple',
    'Albert Hall Museum',
    'Galtaji Temple',
    'Sisodia Rani Garden',
    'Chokhi Dhani',
    'Jaigarh Fort',
  ],
};

// Get locations for a specific destination
export const getLocationsForDestination = (destination) => {
  if (!destination) return [];
  
  // Try exact match first
  if (LOCATIONS_BY_DESTINATION[destination]) {
    return LOCATIONS_BY_DESTINATION[destination];
  }
  
  // Try partial match
  const partialMatch = Object.keys(LOCATIONS_BY_DESTINATION).find(key => 
    key.toLowerCase().includes(destination.toLowerCase()) || 
    destination.toLowerCase().includes(key.toLowerCase())
  );
  
  if (partialMatch) {
    return LOCATIONS_BY_DESTINATION[partialMatch];
  }
  
  return [];
};

// Get all unique locations (for search)
export const ALL_LOCATIONS = [
  ...new Set(
    Object.values(LOCATIONS_BY_DESTINATION)
      .flat()
      .sort()
  )
];
