/**
 * Popular locations/attractions by destination
 * For quick selection when creating day itineraries
 */

// International Destinations
export const LOCATIONS_BY_DESTINATION: Record<string, string[]> = {
  // Popular International
  'Almaty, Kazakhstan': [
    'Medeu Ice Skating Rink',
    'Shymbulak Ski Resort',
    'Kok Tobe Hill',
    'Zenkov Cathedral',
    'Central State Museum',
    'Big Almaty Lake',
    'Green Bazaar',
    'First President Park',
    'Almaty Central Mosque',
    'Panfilov Park',
    'Ascension Cathedral',
    'Almaty Zoo',
    'Charyn Canyon',
    'Kolsai Lakes',
    'Almaty Opera House',
    'Abay Opera House',
    'Republic Square',
    'Independence Monument',
    'Kazakhstan Museum of Arts',
    'Sunkar Falcon Farm',
    'Shakhmardan Yessenov Museum',
    'Almaty Central Park',
    'Kaindy Lake',
    'Tamgaly Petroglyphs',
    'Altyn-Emel National Park',
    'Singing Dune',
    'Issyk Lake',
    'Turgen Gorge',
    'Butakovka Waterfall',
  ],
  'Bali, Indonesia': [
    'Uluwatu Temple',
    'Tanah Lot Temple',
    'Tegalalang Rice Terraces',
    'Sacred Monkey Forest',
    'Mount Batur',
    'Ubud Palace',
    'Seminyak Beach',
    'Kuta Beach',
    'Nusa Dua Beach',
    'Waterbom Bali',
    'Besakih Temple',
    'Tirta Empul Temple',
    'Tegenungan Waterfall',
    'Sekumpul Waterfall',
    'Nusa Penida',
    'Lempuyang Temple',
    'Campuhan Ridge Walk',
    'Bali Safari & Marine Park',
    'Gitgit Waterfall',
    'Jatiluwih Rice Terraces',
    'Aling-Aling Waterfall',
    'Tukad Cepung Waterfall',
    'Kelingking Beach',
    'Crystal Bay',
    'Broken Beach',
    'Angel\'s Billabong',
    'Pura Ulun Danu Bratan',
    'Bali Bird Park',
    'Bali Butterfly Park',
    'Bali Treetop Adventure',
    'Bali Zoo',
    'Garuda Wisnu Kencana',
    'Bali Museum',
    'Pura Taman Saraswati',
    'Yeh Pulu',
  ],
  'Bangkok & Pattaya, Thailand': [
    'Grand Palace Bangkok',
    'Wat Arun',
    'Wat Pho',
    'Floating Market',
    'Chatuchak Market',
    'Khao San Road',
    'Pattaya Beach',
    'Walking Street Pattaya',
    'Coral Island',
    'Nong Nooch Garden',
    'Sanctuary of Truth',
    'Wat Saket (Golden Mount)',
    'Jim Thompson House',
    'Lumpini Park',
    'MBK Center',
    'Siam Paragon',
    'Wat Benchamabophit',
    'Jomtien Beach',
    'Koh Larn',
    'Ripley\'s Believe It or Not',
    'Art in Paradise',
    'Pattaya Floating Market',
    'Mini Siam',
    'Wat Traimit',
    'Wat Suthat',
    'Erawan Shrine',
    'Asiatique The Riverfront',
    'Terminal 21',
    'CentralWorld',
    'Siam Center',
    'Wat Mahathat',
    'Baiyoke Sky Tower',
    'Siam Ocean World',
    'Madame Tussauds Bangkok',
    'Underwater World Pattaya',
    'Koh Samet',
    'Koh Chang',
    'Pattaya Viewpoint',
    'Big Buddha Hill Pattaya',
  ],
  'Dubai, UAE': [
    'Burj Khalifa',
    'Dubai Mall',
    'Dubai Fountain',
    'Palm Jumeirah',
    'Burj Al Arab',
    'Dubai Marina',
    'Gold Souk',
    'Spice Souk',
    'Dubai Creek',
    'Atlantis Aquaventure',
    'Desert Safari',
    'Dubai Frame',
    'Global Village',
    'Mall of Emirates',
    'Ski Dubai',
    'Dubai Aquarium',
    'Dubai Miracle Garden',
    'IMG Worlds of Adventure',
    'Dubai Parks and Resorts',
    'Jumeirah Beach',
    'Dubai Museum',
    'Al Fahidi Historical Neighbourhood',
    'Dubai Opera',
    'La Perle Show',
    'Dubai Marina Walk',
    'The View at The Palm',
    'Dubai Butterfly Garden',
    'Dubai Garden Glow',
    'Motiongate Dubai',
    'Legoland Dubai',
    'Bollywood Parks',
    'Dubai Autodrome',
    'Dubai Water Canal',
    'Al Seef',
    'Bluewaters Island',
    'Ain Dubai',
    'Dubai Festival City',
    'Dubai Festival Mall',
    'Dubai Hills Mall',
    'City Walk',
    'Dubai Outlet Mall',
  ],
  'Malaysia': [
    'Petronas Towers',
    'Batu Caves',
    'Genting Highlands',
    'Langkawi Island',
    'Penang',
    'Cameron Highlands',
    'Malacca',
    'KL Tower',
    'Aquaria KLCC',
    'Sunway Lagoon',
    'Legoland Malaysia',
    'Langkawi Sky Bridge',
    'Penang Hill',
    'Kek Lok Si Temple',
    'Strait of Malacca',
    'Red Square Malacca',
    'Taman Negara',
    'Perhentian Islands',
    'Tioman Island',
    'Mount Kinabalu',
    'Sipadan Island',
    'KLCC Park',
    'Menara KL',
    'Central Market',
    'Chinatown KL',
    'Islamic Arts Museum',
    'National Museum',
    'Sunway Pyramid',
    'Pavilion KL',
    'Suria KLCC',
    'Kuala Lumpur Bird Park',
    'KL Butterfly Park',
    'Twin Towers Skybridge',
    'Penang Street Art',
    'Kek Lok Si Pagoda',
    'Penang National Park',
    'Langkawi Cable Car',
    'Langkawi Underwater World',
    'Redang Island',
    'Mulu Caves',
  ],
  'Maldives': [
    'Male City',
    'Artificial Beach',
    'Grand Friday Mosque',
    'Coral Reefs',
    'Water Sports Center',
    'Local Island Tour',
    'Sandbank Visit',
    'National Museum',
    'Sultan Park',
    'Fish Market',
    'Mulee-aage Palace',
    'Hukuru Miskiy',
    'Snorkeling',
    'Diving',
    'Sunset Cruise',
    'Dolphin Watching',
    'Island Hopping',
    'Underwater Restaurant',
    'Ithaa Undersea Restaurant',
    'Manta Ray Point',
    'Whale Shark Spotting',
    'Biyadhoo Island',
    'Maafushi Island',
    'Fulhadhoo Island',
    'Thulusdhoo Island',
    'Rasdhoo Atoll',
    'Ari Atoll',
    'Baa Atoll',
    'Vaadhoo Island',
    'Glowing Beach',
    'Water Villa',
    'Overwater Bungalow',
    'Spa & Wellness',
    'Fishing Trip',
    'Seaplane Tour',
  ],
  'Mauritius': [
    'Port Louis',
    'Chamarel Seven Colored Earth',
    'Black River Gorges',
    'Le Morne Beach',
    'Ile aux Cerfs',
    'Grand Baie',
    'Pamplemousses Garden',
    'Casela Nature Park',
    'Chamarel Waterfall',
    'Trou aux Cerfs',
    'Blue Bay Marine Park',
    'Flic en Flac Beach',
    'La Vanille Nature Park',
    'SSR Botanical Garden',
    'Aapravasi Ghat',
    'Notre Dame Auxiliatrice',
    'Trou d\'Eau Douce',
    'Ganga Talao',
    'Mont Choisy Beach',
    'Belle Mare Beach',
    'Pereybere Beach',
    'Tamarin Bay',
    'Albion Lighthouse',
    'Eureka House',
    'L\'Aventure du Sucre',
    'Domaine de l\'Etoile',
    'La Vallée des Couleurs',
    'Ile aux Aigrettes',
    'Gabriel Island',
    'Flat Island',
    'Catamaran Cruise',
    'Dolphin Watching',
    'Underwater Waterfall',
    'Seven Colored Earth Geopark',
  ],
  'Phuket & Krabi, Thailand': [
    'Phi Phi Islands',
    'James Bond Island',
    'Phang Nga Bay',
    'Patong Beach',
    'Big Buddha',
    'Old Phuket Town',
    'Railay Beach',
    'Tiger Cave Temple',
    'Emerald Pool',
    'Ao Nang Beach',
    'Kata Beach',
    'Karon Beach',
    'Bangla Road',
    'Wat Chalong',
    'Simon Cabaret Show',
    'Phuket Fantasea',
    'Koh Hong',
    'Koh Poda',
    'Diamond Cave',
    'Hot Springs',
    'Krabi Town',
    'Thung Teao Forest',
    'Koh Phi Phi Don',
    'Koh Phi Phi Leh',
    'Maya Bay',
    'Viking Cave',
    'Monkey Beach',
    'Bamboo Island',
    'Koh Lanta',
    'Koh Rok',
    'Koh Poda',
    'Koh Tup',
    'Koh Mor',
    'Wat Tham Sua',
    'Khao Phanom Bencha',
    'Klong Root',
    'Krabi Hot Springs',
    'Krabi Elephant Sanctuary',
    'Krabi Night Market',
    'Phuket Weekend Market',
  ],
  'Seychelles': [
    'Anse Source d\'Argent',
    'Vallee de Mai',
    'Beau Vallon Beach',
    'Victoria Market',
    'Morne Seychellois',
    'Anse Lazio',
    'Cousin Island',
    'Anse Georgette',
    'Curieuse Island',
    'Aldabra Atoll',
    'Praslin Island',
    'La Digue Island',
    'Sainte Anne Marine Park',
    'Aride Island',
    'Takamaka Bay',
    'Jardin du Roi',
    'Anse Intendance',
    'Anse Takamaka',
    'Anse Marron',
    'Grand Anse',
    'Petite Anse',
    'Coco de Mer',
    'Fond Ferdinand Nature Reserve',
    'Morne Blanc',
    'Cap Ternay',
    'Baie Ternay',
    'Port Launay',
    'Anse Royale',
    'Takamaka Beach',
    'Mahe Island',
    'Bird Island',
    'Fregate Island',
    'North Island',
    'Denis Island',
  ],
  'Singapore': [
    'Marina Bay Sands',
    'Gardens by the Bay',
    'Sentosa Island',
    'Universal Studios',
    'Merlion Park',
    'Orchard Road',
    'Chinatown',
    'Little India',
    'Clarke Quay',
    'Singapore Zoo',
    'Night Safari',
    'Jewel Changi',
    'Singapore Flyer',
    'River Safari',
    'Botanic Gardens',
    'Marina Bay',
    'Helix Bridge',
    'ArtScience Museum',
    'S.E.A. Aquarium',
    'Tiger Sky Tower',
    'Fort Siloso',
    'Haw Par Villa',
    'East Coast Park',
    'Marina Bay Waterfront Promenade',
    'Cloud Forest',
    'Flower Dome',
    'Supertree Grove',
    'OCBC Skyway',
    'Singapore Cable Car',
    'Madame Tussauds Singapore',
    'Trick Eye Museum',
    'Adventure Cove Waterpark',
    'Siloso Beach',
    'Palawan Beach',
    'Tanjong Beach',
    'VivoCity',
    'ION Orchard',
    'Bugis Street',
    'Haji Lane',
    'Arab Street',
    'Singapore River',
    'Boat Quay',
    'Robertson Quay',
  ],
  'Sri Lanka': [
    'Sigiriya Rock',
    'Temple of Tooth',
    'Galle Fort',
    'Yala National Park',
    'Ella',
    'Nuwara Eliya',
    'Tea Plantations',
    'Mirissa Beach',
    'Colombo City',
    'Dambulla Cave Temple',
    'Nine Arch Bridge',
    'Adam\'s Peak',
    'Polonnaruwa',
    'Anuradhapura',
    'Kandy',
    'Bentota',
    'Unawatuna Beach',
    'Hikkaduwa',
    'Sinharaja Forest',
    'Udawalawe National Park',
    'Pinnawala Elephant Orphanage',
    'Ramboda Falls',
    'Horton Plains',
    'World\'s End',
    'Bakers Falls',
    'Royal Botanical Gardens',
    'Kandy Lake',
    'Kandy Market',
    'Peradeniya Gardens',
    'Temple of the Sacred Tooth Relic',
    'Galle Lighthouse',
    'Galle Clock Tower',
    'Dutch Reformed Church',
    'Jungle Beach',
    'Weligama',
    'Arugam Bay',
    'Pasikudah',
    'Nilaveli Beach',
    'Trincomalee',
    'Minneriya National Park',
    'Wilpattu National Park',
    'Bundala National Park',
  ],
  'Thailand': [
    'Grand Palace',
    'Wat Arun',
    'Floating Market',
    'Chiang Mai',
    'Phuket',
    'Ayutthaya',
    'Sukhothai',
    'Khao Sok National Park',
    'Doi Suthep',
    'Elephant Nature Park',
    'Railay Beach',
    'Koh Samui',
    'Koh Phi Phi',
    'Pai',
    'Mae Hong Son',
    'Erawan Falls',
    'Wat Phra Kaew',
    'Chatuchak Weekend Market',
    'Wat Phra That Doi Suthep',
    'Chiang Mai Night Bazaar',
    'Sunday Walking Street',
    'Wat Chedi Luang',
    'Wat Phra Singh',
    'Doi Inthanon',
    'Mae Sa Waterfall',
    'Bua Thong Sticky Waterfalls',
    'Wat Rong Khun (White Temple)',
    'Blue Temple',
    'Black House Museum',
    'Golden Triangle',
    'Long Neck Karen Village',
    'Koh Tao',
    'Koh Phangan',
    'Full Moon Party',
    'Ang Thong National Marine Park',
    'Koh Lanta',
    'Similan Islands',
  ],
  'Vietnam': [
    'Halong Bay',
    'Hanoi Old Quarter',
    'Ho Chi Minh City',
    'Cu Chi Tunnels',
    'Hoi An Ancient Town',
    'Hue Imperial City',
    'Mekong Delta',
    'Sapa',
    'Phong Nha Cave',
    'War Remnants Museum',
    'Notre-Dame Cathedral',
    'Ben Thanh Market',
    'My Son Sanctuary',
    'Ba Na Hills',
    'Golden Bridge',
    'Mui Ne Sand Dunes',
    'Nha Trang',
    'Da Lat',
    'Ban Gioc Falls',
    'Cat Ba Island',
    'Hoan Kiem Lake',
    'Temple of Literature',
    'Ho Chi Minh Mausoleum',
    'One Pillar Pagoda',
    'Water Puppet Show',
    'Dong Xuan Market',
    'Reunification Palace',
    'Saigon Central Post Office',
    'Jade Emperor Pagoda',
    'Mekong River Cruise',
    'Cai Rang Floating Market',
    'Can Tho',
    'My Khe Beach',
    'Po Nagar Cham Towers',
    'Vinpearl Land',
    'Hon Mun Island',
    'Lang Biang Mountain',
    'Crazy House',
    'Datanla Falls',
    'Pongour Falls',
  ],
  'Hongkong & Macau': [
    'Victoria Peak',
    'Hong Kong Disneyland',
    'Ocean Park',
    'Tsim Sha Tsui Promenade',
    'Star Ferry',
    'Temple Street Night Market',
    'Big Buddha (Tian Tan)',
    'Macau Tower',
    'Ruins of St. Paul\'s',
    'Senado Square',
    'Venetian Macau',
    'A-Ma Temple',
    'Coloane Village',
    'Ngong Ping 360',
    'Hong Kong Museum',
    'Lantau Island',
    'Wong Tai Sin Temple',
    'Symphony of Lights',
    'Stanley Market',
    'Repulse Bay',
    'Macau Fisherman\'s Wharf',
    'Guia Fortress',
    'Taipa Village',
    'House of Dancing Water',
    'Peak Tram',
    'Sky100',
    'Hong Kong Observation Wheel',
    'Avenue of Stars',
    'Clock Tower',
    'Space Museum',
    'Science Museum',
    'History Museum',
    'Mong Kok',
    'Causeway Bay',
    'Central',
    'Sheung Wan',
    'Aberdeen',
    'Tai O Fishing Village',
    'Cheung Chau Island',
    'Lamma Island',
    'Macau Grand Prix Museum',
    'Macau Science Center',
    'Kun Iam Statue',
    'Taipa Houses Museum',
  ],
  'Japan': [
    'Tokyo Tower',
    'Mount Fuji',
    'Senso-ji Temple',
    'Osaka Castle',
    'Fushimi Inari Shrine',
    'Hiroshima Peace Memorial',
    'Nara Park',
    'Universal Studios Japan',
    'Tokyo Disneyland',
    'Kyoto Imperial Palace',
    'Arashiyama Bamboo Grove',
    'Golden Pavilion (Kinkaku-ji)',
    'Shinjuku Gyoen',
    'Akihabara',
    'Tokyo Skytree',
    'Shibuya Crossing',
    'Meiji Shrine',
    'Tokyo National Museum',
    'Hakone',
    'Nikko',
    'Takayama',
    'Kanazawa',
    'Miyajima Island',
    'Osaka Aquarium',
    'Dotonbori',
    'Tokyo DisneySea',
    'Harajuku',
    'Shibuya',
    'Ginza',
    'Roppongi',
    'Tsukiji Fish Market',
    'TeamLab Borderless',
    'TeamLab Planets',
    'Ueno Park',
    'Asakusa',
    'Odaiba',
    'Tokyo Station',
    'Imperial Palace',
    'Yoyogi Park',
    'Hachiko Statue',
    'Kiyomizu-dera',
    'Gion District',
    'Philosopher\'s Path',
    'Nijo Castle',
    'Kinkaku-ji',
    'Fushimi Inari',
    'Itsukushima Shrine',
    'Himeji Castle',
    'Kumamoto Castle',
  ],
  'Turkey': [
    'Hagia Sophia',
    'Blue Mosque',
    'Topkapi Palace',
    'Cappadocia',
    'Pamukkale',
    'Ephesus',
    'Grand Bazaar',
    'Bosphorus Cruise',
    'Galata Tower',
    'Basilica Cistern',
    'Troy',
    'Antalya Old Town',
    'Goreme Open Air Museum',
    'Sultanahmet Square',
    'Dolmabahce Palace',
    'Istanbul Archaeology Museum',
    'Spice Bazaar',
    'Hot Air Balloon Ride',
    'Derinkuyu Underground City',
    'Ihlara Valley',
    'Aspendos Theatre',
    'Perge',
    'Side',
    'Bodrum',
    'Kusadasi',
    'Suleymaniye Mosque',
    'Chora Church',
    'Rumeli Fortress',
    'Ortakoy Mosque',
    'Maiden\'s Tower',
    'Taksim Square',
    'Istiklal Avenue',
    'Pierre Loti Hill',
    'Eyup Sultan Mosque',
    'Uchisar Castle',
    'Pasabag Valley',
    'Devrent Valley',
    'Love Valley',
    'Red Valley',
    'Rose Valley',
    'Kaymakli Underground City',
    'Ozkonak Underground City',
    'Hierapolis',
    'Cleopatra\'s Pool',
    'Kaleici',
    'Duden Waterfalls',
    'Kursunlu Waterfall',
    'Olympos',
    'Myra',
    'Patara Beach',
  ],
  'Baku, Azerbaijan': [
    'Flame Towers',
    'Old City (Icherisheher)',
    'Heydar Aliyev Center',
    'Baku Boulevard',
    'Maiden Tower',
    'Palace of the Shirvanshahs',
    'Ateshgah Fire Temple',
    'Gobustan Rock Art',
    'Mud Volcanoes',
    'Carpet Museum',
    'Nizami Street',
    'Yanar Dag',
    'Bibi-Heybat Mosque',
    'Azerbaijan National Museum',
    'Fountain Square',
    'Shirvan National Park',
    'Absheron Peninsula',
    'Little Venice',
    'Baku Crystal Hall',
    'Martyrs\' Lane',
    'Azerbaijan Carpet Museum',
    'Museum of Modern Art',
    'National Art Museum',
    'Baku Museum Center',
    'Villa Petrolea',
    'Baku TV Tower',
    'Baku Ferris Wheel',
    'Baku Zoo',
    'Baku Botanical Garden',
    'Shirvanshahs\' Palace Complex',
    'Juma Mosque',
    'Muhammad Mosque',
    'Gosha Gala Gate',
    'Baku Funicular',
    'Baku Seaside Park',
    'Gobustan National Park',
    'Qobustan',
    'Mardakan Castle',
    'Ramana Castle',
    'Nardaran',
  ],
  'Georgia': [
    'Tbilisi Old Town',
    'Narikala Fortress',
    'Svetitskhoveli Cathedral',
    'Uplistsikhe Cave Town',
    'Gergeti Trinity Church',
    'Ananuri Fortress',
    'Sighnaghi',
    'Kazbegi',
    'Batumi Boulevard',
    'Vardzia Cave Monastery',
    'Prometheus Cave',
    'Peace Bridge',
    'Bridge of Peace',
    'Mtatsminda Park',
    'Jvari Monastery',
    'Gudauri',
    'Bakuriani',
    'Borjomi',
    'Mtskheta',
    'David Gareja',
    'Shatili',
    'Omalo',
    'Sulfur Baths',
    'Rike Park',
    'Tbilisi Botanical Garden',
    'National Museum of Georgia',
    'Georgian National Museum',
    'Rustaveli Avenue',
    'Freedom Square',
    'Holy Trinity Cathedral',
    'Metekhi Church',
    'Anchiskhati Basilica',
    'Batumi Botanical Garden',
    'Batumi Dolphinarium',
    'Alphabetic Tower',
    'Europe Square',
    'Gonio Fortress',
    'Rabati Castle',
    'Borjomi Central Park',
    'Borjomi-Kharagauli National Park',
    'Martvili Canyon',
    'Okatse Canyon',
    'Sataplia Cave',
    'Kutaisi',
    'Bagrati Cathedral',
    'Gelati Monastery',
  ],
  'Philippines': [
    'Boracay Island',
    'Palawan',
    'El Nido',
    'Chocolate Hills',
    'Banaue Rice Terraces',
    'Intramuros',
    'Rizal Park',
    'Taal Volcano',
    'Mayon Volcano',
    'Coron Island',
    'Puerto Princesa Underground River',
    'Manila Bay',
    'Bohol',
    'Tubbataha Reef',
    'Siargao',
    'Cebu',
    'Donsol',
    'Vigan',
    'Sagada',
    'Banaue',
    'Kawasan Falls',
    'Pagsanjan Falls',
    'Manila Ocean Park',
    'Fort Santiago',
    'White Beach Boracay',
    'Puka Shell Beach',
    'Diniwid Beach',
    'Bulabog Beach',
    'Big Lagoon',
    'Small Lagoon',
    'Secret Lagoon',
    'Hidden Beach',
    'Nacpan Beach',
    'Seven Commandos Beach',
    'Kayangan Lake',
    'Twin Lagoon',
    'Barracuda Lake',
    'Siete Pecados',
    'Malcapuya Island',
    'Banana Island',
    'Pass Island',
    'Tubbataha Reefs Natural Park',
    'Apo Reef',
    'Ticao Island',
    'Donsol Whale Shark Interaction',
    'Butanding Interaction',
    'Vigan Heritage Village',
    'Calle Crisologo',
    'Bantay Bell Tower',
    'Sagada Hanging Coffins',
    'Sumaguing Cave',
    'Echo Valley',
    'Bomod-ok Falls',
    'Bokong Falls',
  ],
};


// Get locations for a specific destination
export const getLocationsForDestination = (destination?: string | null): string[] => {
  if (!destination) return [];

  // Try exact match first
  if (LOCATIONS_BY_DESTINATION[destination]) {
    return LOCATIONS_BY_DESTINATION[destination];
  }

  // Try partial match
  const partialMatch = Object.keys(LOCATIONS_BY_DESTINATION).find(key =>
    key.toLowerCase().includes(destination.toLowerCase()) ||
    destination.toLowerCase().includes(key.toLowerCase())
  );

  if (partialMatch) {
    return LOCATIONS_BY_DESTINATION[partialMatch];
  }

  return [];
};

// Get all unique locations (for search)
export const ALL_LOCATIONS = [
  ...new Set(
    Object.values(LOCATIONS_BY_DESTINATION)
      .flat()
      .sort()
  )
];
